/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.Customer.Customer;
import Business.Pharmacy.Pharmacy;


/**
 *
 * @author Vini
 */
public class CustomerAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    Pharmacy pharmacy;
    EcoSystem system;
    Customer customer;
    
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public CustomerAreaJPanel(JPanel userProcessContainer, UserAccount useraccount, EcoSystem system) {
        initComponents();        
        this.userProcessContainer = userProcessContainer;  
        this.userAccount = useraccount;
        this.system = system;
        
        for(Customer c : system.getCustomerDirectory().getCustomerList() )
        {
            
                if(c.getName() == null ? useraccount.getEmployee().getName() == null : c.getName().equals(useraccount.getEmployee().getName()))
                {
                    this.customer = c;
                }
           
        }
        
        txtName.setText(this.customer.getName());
        txtAddress.setText(this.customer.getAddress());
        txtPhone.setText(this.customer.getPhone());
        
        valueLabel.setText(this.customer.getName());
        jComboPharmacy.addItem("");
        for(Pharmacy p : system.getPharmacyDirectory().getPharmacyList())
        {
            jComboPharmacy.addItem(p.getName());
        }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboPharmacy = new javax.swing.JComboBox<>();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Address:");
        add(jLabel4);
        jLabel4.setBounds(111, 273, 110, 20);

        txtAddress.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtAddress);
        txtAddress.setBounds(261, 273, 150, 16);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Name:");
        add(jLabel5);
        jLabel5.setBounds(111, 193, 120, 14);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Work Area");
        add(jLabel1);
        jLabel1.setBounds(41, 0, 580, 28);

        jComboPharmacy.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jComboPharmacy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPharmacyActionPerformed(evt);
            }
        });
        add(jComboPharmacy);
        jComboPharmacy.setBounds(241, 94, 170, 20);

        enterpriseLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        enterpriseLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        enterpriseLabel.setText("Welcome! ");
        add(enterpriseLabel);
        enterpriseLabel.setBounds(160, 55, 108, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Update Details");
        add(jLabel6);
        jLabel6.setBounds(211, 149, 89, 17);

        valueLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel);
        valueLabel.setBounds(286, 55, 118, 22);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Review Orders");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(120, 330, 118, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Choose a Pharmacy:");
        add(jLabel2);
        jLabel2.setBounds(124, 96, 107, 21);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Phone:");
        add(jLabel3);
        jLabel3.setBounds(111, 241, 110, 14);

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtName);
        txtName.setBounds(261, 183, 150, 16);

        txtPhone.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtPhone);
        txtPhone.setBounds(261, 231, 150, 16);

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(250, 330, 118, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/MicrosoftTeams-image (1).png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(0, 10, 1440, 790);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPharmacyActionPerformed
        // TODO add your handling code here:
        if(jComboPharmacy.getSelectedItem() != "")
        {
            String phar = jComboPharmacy.getSelectedItem().toString();
            pharmacy = system.getPharmacyDirectory().findPharmacy(phar);
            CustomerOrderAction cpo = new CustomerOrderAction(userProcessContainer, customer, pharmacy);
            userProcessContainer.add("CustomerOrder", cpo);
            CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_jComboPharmacyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CustomerSummaryJPanell lcj = new CustomerSummaryJPanell(userProcessContainer, userAccount, system);
        userProcessContainer.add("CustomerOrder", lcj);
        CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if((txtAddress.getText() == "") || (txtPhone.getText() == "") )
        {
            JOptionPane.showMessageDialog(null,"Please fill all values!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else
        {
            customer.setAddress(txtAddress.getText());
            customer.setPhone(txtPhone.getText());
          
                    
        }
        valueLabel.setText(pharmacy.getName());
    }//GEN-LAST:event_btnSubmitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboPharmacy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
