/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.Customer.CustomerStore;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author dhrit
 */
public class AddCustomerJPanel extends javax.swing.JPanel {

    private CustomerStore custDirectory;
    private JPanel container;
    private EcoSystem system;
    
    Customer cust = new Customer();
    /**
     * Creates new form AddCustomerJPanel
     */
    public AddCustomerJPanel(JPanel container, EcoSystem system, CustomerStore custDir) {
        initComponents();
        this.custDirectory = custDir;
        this.system = system;
        this.container = container;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddCustomer = new javax.swing.JLabel();
        lblCustName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        lblCustUserName = new javax.swing.JLabel();
        txtCustomerUserName = new javax.swing.JTextField();
        lblCustPass = new javax.swing.JLabel();
        txtCustomerPassword = new javax.swing.JPasswordField();
        pbCustomerPassword = new javax.swing.JProgressBar();
        lblCustContact = new javax.swing.JLabel();
        txtCustomerContact = new javax.swing.JTextField();
        lblCustAddr = new javax.swing.JLabel();
        txtCustomerAddress = new javax.swing.JTextField();
        btnAddCustomerBack = new javax.swing.JButton();
        btnCustomerAdd = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddCustomer.setBackground(new java.awt.Color(204, 255, 255));
        lblAddCustomer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAddCustomer.setForeground(new java.awt.Color(0, 51, 51));
        lblAddCustomer.setText("Customer Information");
        add(lblAddCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        lblCustName.setBackground(new java.awt.Color(204, 255, 255));
        lblCustName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCustName.setForeground(new java.awt.Color(0, 51, 51));
        lblCustName.setText("Name :");
        add(lblCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        txtCustomerName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtCustomerName.setForeground(new java.awt.Color(0, 51, 51));
        txtCustomerName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 69, 340, -1));

        lblCustUserName.setBackground(new java.awt.Color(204, 255, 255));
        lblCustUserName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCustUserName.setForeground(new java.awt.Color(0, 51, 51));
        lblCustUserName.setText("Set Username :");
        add(lblCustUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        txtCustomerUserName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtCustomerUserName.setForeground(new java.awt.Color(0, 51, 51));
        txtCustomerUserName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(txtCustomerUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 340, -1));

        lblCustPass.setBackground(new java.awt.Color(204, 255, 255));
        lblCustPass.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCustPass.setForeground(new java.awt.Color(0, 51, 51));
        lblCustPass.setText("Set Password :");
        add(lblCustPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        txtCustomerPassword.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtCustomerPassword.setForeground(new java.awt.Color(0, 51, 51));
        txtCustomerPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCustomerPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerPasswordActionPerformed(evt);
            }
        });
        txtCustomerPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustomerPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerPasswordKeyTyped(evt);
            }
        });
        add(txtCustomerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 131, 340, -1));

        pbCustomerPassword.setBackground(new java.awt.Color(204, 255, 255));
        pbCustomerPassword.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        pbCustomerPassword.setForeground(new java.awt.Color(0, 51, 51));
        pbCustomerPassword.setMaximum(13);
        pbCustomerPassword.setMinimum(1);
        pbCustomerPassword.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pbCustomerPasswordStateChanged(evt);
            }
        });
        add(pbCustomerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 162, 127, 10));

        lblCustContact.setBackground(new java.awt.Color(204, 255, 255));
        lblCustContact.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCustContact.setForeground(new java.awt.Color(0, 51, 51));
        lblCustContact.setText("Phone No:");
        add(lblCustContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        txtCustomerContact.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtCustomerContact.setForeground(new java.awt.Color(0, 51, 51));
        txtCustomerContact.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(txtCustomerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 187, 340, -1));

        lblCustAddr.setBackground(new java.awt.Color(204, 255, 255));
        lblCustAddr.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCustAddr.setForeground(new java.awt.Color(0, 51, 51));
        lblCustAddr.setText("Address:");
        add(lblCustAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        txtCustomerAddress.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtCustomerAddress.setForeground(new java.awt.Color(0, 51, 51));
        txtCustomerAddress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(txtCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 340, -1));

        btnAddCustomerBack.setBackground(new java.awt.Color(204, 255, 255));
        btnAddCustomerBack.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnAddCustomerBack.setForeground(new java.awt.Color(0, 51, 51));
        btnAddCustomerBack.setText("Back");
        btnAddCustomerBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddCustomerBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerBackActionPerformed(evt);
            }
        });
        add(btnAddCustomerBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 60, -1));

        btnCustomerAdd.setBackground(new java.awt.Color(204, 255, 255));
        btnCustomerAdd.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnCustomerAdd.setForeground(new java.awt.Color(0, 51, 51));
        btnCustomerAdd.setText("Add");
        btnCustomerAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCustomerAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerAddActionPerformed(evt);
            }
        });
        add(btnCustomerAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 60, -1));
    }// </editor-fold>//GEN-END:initComponents
   public void resetFields() {
        txtCustomerAddress.setText("");
        txtCustomerContact.setText("");
        txtCustomerName.setText("");
        txtCustomerPassword.setText("");
        txtCustomerUserName.setText("");
        pbCustomerPassword.setValue(0);
    }
    private void txtCustomerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerPasswordActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCustomerPasswordActionPerformed

    private void txtCustomerPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerPasswordKeyReleased
        // TODO add your handling code here:
        //          int pwSize = pwCustPass.getText().length();
        //        System.out.println("PassKeyReleased PwSize :: "+pwSize);
        //        pbCustPassStr.setValue(pwSize);
    }//GEN-LAST:event_txtCustomerPasswordKeyReleased

    private void txtCustomerPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerPasswordKeyTyped
        // TODO add your handling code here:
        int pwSize = txtCustomerPassword.getText().length();
        //        System.out.println("PassKeyTyped PwSize :: "+pwSize);
        pbCustomerPassword.setValue(pwSize);
    }//GEN-LAST:event_txtCustomerPasswordKeyTyped

    private void pbCustomerPasswordStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pbCustomerPasswordStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_pbCustomerPasswordStateChanged

    private void btnAddCustomerBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageCustomersJPanel manageCustomersJPanel = (ManageCustomersJPanel) component;
        manageCustomersJPanel.populateCustomerListTable();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnAddCustomerBackActionPerformed

    private void btnCustomerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerAddActionPerformed
        // TODO add your handling code here:

        String custName = txtCustomerName.getText();
        String custContact = txtCustomerContact.getText();
        String custAddr = txtCustomerAddress.getText();
        String custUserName = txtCustomerUserName.getText();
        String custPass = String.valueOf(txtCustomerPassword.getPassword());

        if( custName.isEmpty() || custContact.isEmpty() || custAddr.isEmpty()  ||
            custUserName.isEmpty() || custPass.isEmpty()  ) {
            JOptionPane.showMessageDialog(null, "Kindly Enter all the required fields!");
        }   else if (!system.validateMobileNo(custContact)) {
            JOptionPane.showMessageDialog(null, "Kindly enter a Valid Contact Number.");
        }    else if (!system.getUserAccountDirectory().checkIfUsernameIsUnique(custUserName)) {
            JOptionPane.showMessageDialog(null, "Entered User Name is already mapped to another Customer");
        }     else if (!custDirectory.isContactNoUnique(custContact)) {
            JOptionPane.showMessageDialog(null, "Entered Contact No is already mapped to another Customer.");
        }   else {

            cust.setCustID(custDirectory.genCustID() );
            cust.setCustName(custName);
            cust.setCustAddr(custAddr);
            cust.setCustContact(custContact);
            custDirectory.addCustomer(cust);
            Employee employee = system.getEmployeeDirectory().createEmployee(cust.getCustID());
            system.setCustomerDirectory(custDirectory);
            UserAccount account = system.getUserAccountDirectory().createUserAccount(custUserName, custPass, employee, new CustomerRole());
            JOptionPane.showMessageDialog(null, "New Customer "+account.getUsername()+" added to the System Successfully!");
            resetFields();
        }
    }//GEN-LAST:event_btnCustomerAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomerBack;
    private javax.swing.JButton btnCustomerAdd;
    private javax.swing.JLabel lblAddCustomer;
    private javax.swing.JLabel lblCustAddr;
    private javax.swing.JLabel lblCustContact;
    private javax.swing.JLabel lblCustName;
    private javax.swing.JLabel lblCustPass;
    private javax.swing.JLabel lblCustUserName;
    private javax.swing.JProgressBar pbCustomerPassword;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerContact;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JPasswordField txtCustomerPassword;
    private javax.swing.JTextField txtCustomerUserName;
    // End of variables declaration//GEN-END:variables
}
