/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.Customer.Customer;
import Business.Pharmacy.Pharmacy;


/**
 *
 * @author juile
 */
public class CustomerAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    Pharmacy pharmacy;
    EcoSystem system;
    Customer customer;
    
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public CustomerAreaJPanel(JPanel userProcessContainer, UserAccount useraccount, EcoSystem system) {
        initComponents();        
        this.userProcessContainer = userProcessContainer;  
        this.userAccount = useraccount;
        this.system = system;
        
        for(Customer c : system.getCustomerDirectory().getCustomerList() )
        {
            
                if(c.getCustomerName() == null ? useraccount.getEmployee().getEmployeeName() == null : c.getCustomerName().equals(useraccount.getEmployee().getEmployeeName()))

                {
                    this.customer = c;
                }
           
        }
        
        CustomerNametext.setText(this.customer.getCustomerName());

        CustomerAddressText.setText(this.customer.getCustomerAddress());
        CustomerContactText.setText(this.customer.getCustomerContactNo());

        
        valueLabel.setText(this.customer.getCustomerName());
        PharmacyComboBox.addItem("");
        for(Pharmacy p : system.getPharmacyDirectory().getPharmacyList())
        {

            PharmacyComboBox.addItem(p.getPharmacyName());

        }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerAddressLabel = new javax.swing.JLabel();
        CustomerAddressText = new javax.swing.JTextField();
        CustomerNameLabel = new javax.swing.JLabel();
        CustomerWorkAreaLabel = new javax.swing.JLabel();
        PharmacyComboBox = new javax.swing.JComboBox<>();
        WelcomeLabel = new javax.swing.JLabel();
        UpdateDetailLabels = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        ReviewOrdersButton = new javax.swing.JButton();
        PharmacyLabel = new javax.swing.JLabel();
        CustomerContactNoLabel = new javax.swing.JLabel();
        CustomerNametext = new javax.swing.JTextField();
        CustomerContactText = new javax.swing.JTextField();
        SubmitOrdersButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setLayout(null);

        CustomerAddressLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CustomerAddressLabel.setText("Address:");
        add(CustomerAddressLabel);
        CustomerAddressLabel.setBounds(80, 570, 110, 20);


        CustomerAddressText.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CustomerAddressText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(CustomerAddressText);

        CustomerAddressText.setBounds(250, 570, 180, 20);

        CustomerNameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CustomerNameLabel.setText("Name:");
        add(CustomerNameLabel);
        CustomerNameLabel.setBounds(80, 370, 120, 17);

        CustomerWorkAreaLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        CustomerWorkAreaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CustomerWorkAreaLabel.setText("Customer Work Area");
        add(CustomerWorkAreaLabel);
        CustomerWorkAreaLabel.setBounds(510, 40, 580, 42);


        PharmacyComboBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        PharmacyComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PharmacyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PharmacyComboBoxActionPerformed(evt);
            }
        });
        add(PharmacyComboBox);

        PharmacyComboBox.setBounds(210, 200, 230, 30);

        WelcomeLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        WelcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        WelcomeLabel.setText("Welcome! ");
        add(WelcomeLabel);
        WelcomeLabel.setBounds(70, 110, 130, 28);

        UpdateDetailLabels.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        UpdateDetailLabels.setText("Customer details");
        add(UpdateDetailLabels);
        UpdateDetailLabels.setBounds(170, 280, 130, 30);

        valueLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel);
        valueLabel.setBounds(230, 110, 118, 28);

        ReviewOrdersButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        ReviewOrdersButton.setText("Review Orders");
        ReviewOrdersButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReviewOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewOrdersButtonActionPerformed(evt);
            }
        });
        add(ReviewOrdersButton);

        ReviewOrdersButton.setBounds(70, 680, 160, 40);

        PharmacyLabel.setBackground(new java.awt.Color(255, 255, 255));
        PharmacyLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PharmacyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PharmacyLabel.setText("Select a Pharmacy:");
        add(PharmacyLabel);
        PharmacyLabel.setBounds(-20, 190, 270, 50);

        CustomerContactNoLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CustomerContactNoLabel.setText("Phone:");
        add(CustomerContactNoLabel);
        CustomerContactNoLabel.setBounds(80, 460, 110, 30);
        CustomerContactNoLabel.getAccessibleContext().setAccessibleName("Contact No:");

        CustomerNametext.setEditable(false);
        CustomerNametext.setBackground(new java.awt.Color(255, 255, 255));
        CustomerNametext.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CustomerNametext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(CustomerNametext);
        CustomerNametext.setBounds(250, 370, 180, 20);

        CustomerContactText.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CustomerContactText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(CustomerContactText);

        CustomerContactText.setBounds(250, 470, 180, 20);

        SubmitOrdersButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        SubmitOrdersButton.setText("Submit");
        SubmitOrdersButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitOrdersButtonActionPerformed(evt);
            }
        });
        add(SubmitOrdersButton);

        SubmitOrdersButton.setBounds(250, 680, 160, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/online-pharmacy-vector-concept-design.jpg"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(280, 120, 1150, 680);

    }// </editor-fold>//GEN-END:initComponents

    private void PharmacyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PharmacyComboBoxActionPerformed
        // TODO add your handling code here:
        if(PharmacyComboBox.getSelectedItem() != "")
        {
            String phar = PharmacyComboBox.getSelectedItem().toString();
            pharmacy = system.getPharmacyDirectory().findPharmacy(phar);
            CustomerOrderAction cpo = new CustomerOrderAction(userProcessContainer, customer, pharmacy);
            userProcessContainer.add("CustomerOrder", cpo);
            CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_PharmacyComboBoxActionPerformed

    private void ReviewOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewOrdersButtonActionPerformed
        // TODO add your handling code here:
        CustomerSummaryJPanell lcj = new CustomerSummaryJPanell(userProcessContainer, userAccount, system);
        userProcessContainer.add("CustomerOrder", lcj);
        CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ReviewOrdersButtonActionPerformed

    private void SubmitOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitOrdersButtonActionPerformed
        // TODO add your handling code here:
        if((CustomerAddressText.getText() == "") || (CustomerContactText.getText() == "") )
        {
            JOptionPane.showMessageDialog(null,"Please fill all values!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else
        {

            customer.setCustomerAddress(CustomerAddressText.getText());
            customer.setCustomerContactNo(CustomerContactText.getText());
          
                    
        }
        valueLabel.setText(pharmacy.getPharmacyName());

    }//GEN-LAST:event_SubmitOrdersButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustomerAddressLabel;
    private javax.swing.JTextField CustomerAddressText;
    private javax.swing.JLabel CustomerContactNoLabel;
    private javax.swing.JTextField CustomerContactText;
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JTextField CustomerNametext;
    private javax.swing.JLabel CustomerWorkAreaLabel;
    private javax.swing.JComboBox<String> PharmacyComboBox;
    private javax.swing.JLabel PharmacyLabel;
    private javax.swing.JButton ReviewOrdersButton;
    private javax.swing.JButton SubmitOrdersButton;
    private javax.swing.JLabel UpdateDetailLabels;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
