/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.Customer.CustomerStore;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dhrit
 */
public class ManageCustomersJPanel extends javax.swing.JPanel {
    public CustomerStore custDirectory;
    public JPanel container;
    public EcoSystem system;
    /**
     * Creates new form UpdateCustomersJPanel
     */
    public ManageCustomersJPanel(JPanel userProcessContainer, EcoSystem system, CustomerStore custDirectory) {
        initComponents();
        this.system = system;
        this.custDirectory = custDirectory;
        this.container = userProcessContainer;
        populateCustomerListTable();
    }
    
    public void populateCustomerListTable() {
        DefaultTableModel model = (DefaultTableModel) tblCustomersList.getModel();
        model.setRowCount(0);
        for (UserAccount userAcc : system.getUserAccountDirectory().getUserAccountList()) {
            for (Customer customer : custDirectory.getCustDir()) {
                if (customer.getCustID().equalsIgnoreCase(userAcc.getEmployee().getName())) {
                    Object[] row = new Object[5];
                    row[0] = customer.getCustID();
                    row[1] = userAcc.getUsername();
                    row[2] = customer.getCustName();
                    row[3] = customer.getCustContact();
                    row[4] = customer.getCustAddr();
                    model.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomersList = new javax.swing.JTable();
        btnViewCustomer = new javax.swing.JButton();
        btnDeleteCustomer = new javax.swing.JButton();
        btnAddCustomer = new javax.swing.JButton();
        btnBackCust = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer List");

        tblCustomersList.setBackground(new java.awt.Color(255, 255, 204));
        tblCustomersList.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblCustomersList.setForeground(new java.awt.Color(0, 51, 51));
        tblCustomersList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer No", "User Name", "Customer Name", "Phone Number", "Customer Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomersList);

        btnViewCustomer.setBackground(new java.awt.Color(204, 255, 255));
        btnViewCustomer.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnViewCustomer.setForeground(new java.awt.Color(0, 51, 51));
        btnViewCustomer.setText("View");
        btnViewCustomer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCustomerActionPerformed(evt);
            }
        });

        btnDeleteCustomer.setBackground(new java.awt.Color(204, 255, 255));
        btnDeleteCustomer.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnDeleteCustomer.setForeground(new java.awt.Color(0, 51, 51));
        btnDeleteCustomer.setText("Delete");
        btnDeleteCustomer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });

        btnAddCustomer.setBackground(new java.awt.Color(204, 255, 255));
        btnAddCustomer.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnAddCustomer.setForeground(new java.awt.Color(0, 51, 51));
        btnAddCustomer.setText("Add");
        btnAddCustomer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnBackCust.setBackground(new java.awt.Color(204, 255, 255));
        btnBackCust.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnBackCust.setForeground(new java.awt.Color(0, 51, 51));
        btnBackCust.setText("Back");
        btnBackCust.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBackCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackCustActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(jLabel1)
                .addContainerGap(305, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnViewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnDeleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackCust, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCustomer)
                    .addComponent(btnBackCust)
                    .addComponent(btnViewCustomer)
                    .addComponent(btnDeleteCustomer))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCustomerActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCustomersList.getSelectedRow();
        int count = tblCustomersList.getSelectedRowCount();
        if (count == 1) {
            if (selectedRow >= 0) {
                CardLayout layout = (CardLayout) container.getLayout();
                Customer customer = custDirectory.getCustomerId(selectedRow);
                ViewUpdateCustomerJPanel viewUpdateCustomerJPanel = new ViewUpdateCustomerJPanel(system, container, customer, custDirectory);
                container.add(viewUpdateCustomerJPanel);
                layout.next(container); 
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a Row to continue.");
        }
    }//GEN-LAST:event_btnViewCustomerActionPerformed

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCustomersList.getSelectedRow();
        int count = tblCustomersList.getSelectedRowCount();
        if (count == 1) {
            if (selectedRow >= 0) {
                int selectionButton = JOptionPane.YES_NO_OPTION;
                int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??", "Warning", selectionButton);
                if (selectionResult == JOptionPane.YES_OPTION) {
                    custDirectory.deleteCustomer(selectedRow, system);
                    populateCustomerListTable();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a Row to continue.");
        }
    }//GEN-LAST:event_btnDeleteCustomerActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        AddCustomerJPanel createCustomersJPanel = new AddCustomerJPanel(container, system, custDirectory);
        container.add(createCustomersJPanel);
        layout.next(container);
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnBackCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackCustActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackCustActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnBackCust;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnViewCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomersList;
    // End of variables declaration//GEN-END:variables
}
