/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.Customer.CustomerStore;
import Business.EcoSystem;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dhrit
 */
public class ViewUpdateCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomerJPanel
     */
    
    public CustomerStore customerDirectory;
    public JPanel container;
    public Customer customer;
    private final EcoSystem system;
    private String currentPhoneNo;
    
    public ViewUpdateCustomerJPanel(EcoSystem system, JPanel container, Customer customer, CustomerStore customerDirectory) {
        
        initComponents();
        this.customerDirectory = customerDirectory;
        this.container = container;
        this.customer = customer;
        this.system = system;
        this.currentPhoneNo = customer.getCustContact(); 
        
        txtCustomerID.setText(customer.getCustID());
        txtCustomerAddress.setText(customer.getCustAddr());
        txtCustomerContact.setText(customer.getCustContact());
        txtCustomerName.setText(customer.getCustName());
        
        disableEdit();
    }
private void disableEdit(){
    txtCustomerID.setEditable(false);
    txtCustomerAddress.setEditable(false);
    txtCustomerContact.setEditable(false);
    txtCustomerName.setEditable(false);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCustomerContact = new javax.swing.JTextField();
        lblViewUpdateCust = new javax.swing.JLabel();
        lblCustAddr = new javax.swing.JLabel();
        lblCustName = new javax.swing.JLabel();
        txtCustomerAddress = new javax.swing.JTextField();
        lblCustContact = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        btnBack0 = new javax.swing.JButton();
        btnCustomerChanges = new javax.swing.JButton();
        btnUpdateCustomer = new javax.swing.JButton();
        lblCustID = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));

        txtCustomerContact.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtCustomerContact.setForeground(new java.awt.Color(0, 51, 51));
        txtCustomerContact.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblViewUpdateCust.setBackground(new java.awt.Color(204, 255, 255));
        lblViewUpdateCust.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblViewUpdateCust.setForeground(new java.awt.Color(0, 51, 51));
        lblViewUpdateCust.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewUpdateCust.setText("Customer Information");

        lblCustAddr.setBackground(new java.awt.Color(204, 255, 255));
        lblCustAddr.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblCustAddr.setForeground(new java.awt.Color(0, 51, 51));
        lblCustAddr.setText("Address:");

        lblCustName.setBackground(new java.awt.Color(204, 255, 255));
        lblCustName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblCustName.setForeground(new java.awt.Color(0, 51, 51));
        lblCustName.setText("Name:");

        txtCustomerAddress.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtCustomerAddress.setForeground(new java.awt.Color(0, 51, 51));
        txtCustomerAddress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCustContact.setBackground(new java.awt.Color(204, 255, 255));
        lblCustContact.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblCustContact.setForeground(new java.awt.Color(0, 51, 51));
        lblCustContact.setText("Contact No :");

        txtCustomerName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtCustomerName.setForeground(new java.awt.Color(0, 51, 51));
        txtCustomerName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnBack0.setBackground(new java.awt.Color(204, 255, 255));
        btnBack0.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnBack0.setForeground(new java.awt.Color(0, 51, 51));
        btnBack0.setText("Back");
        btnBack0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack0ActionPerformed(evt);
            }
        });

        btnCustomerChanges.setBackground(new java.awt.Color(204, 255, 255));
        btnCustomerChanges.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnCustomerChanges.setForeground(new java.awt.Color(0, 51, 51));
        btnCustomerChanges.setText("Add");
        btnCustomerChanges.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCustomerChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerChangesActionPerformed(evt);
            }
        });

        btnUpdateCustomer.setBackground(new java.awt.Color(204, 255, 255));
        btnUpdateCustomer.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnUpdateCustomer.setForeground(new java.awt.Color(0, 51, 51));
        btnUpdateCustomer.setText("Update");
        btnUpdateCustomer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerActionPerformed(evt);
            }
        });

        lblCustID.setBackground(new java.awt.Color(204, 255, 255));
        lblCustID.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblCustID.setForeground(new java.awt.Color(0, 51, 51));
        lblCustID.setText("Customer ID :");

        txtCustomerID.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtCustomerID.setForeground(new java.awt.Color(0, 51, 51));
        txtCustomerID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCustID)
                            .addComponent(lblCustName)
                            .addComponent(lblCustContact)
                            .addComponent(lblCustAddr))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCustomerID, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                            .addComponent(txtCustomerName)
                            .addComponent(txtCustomerContact)
                            .addComponent(txtCustomerAddress)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCustomerChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(btnBack0, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(lblViewUpdateCust)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblViewUpdateCust)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomerContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustID))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustName))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustAddr)
                    .addComponent(txtCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack0)
                    .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCustomerChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack0ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageCustomersJPanel manageCustomersJPanel = (ManageCustomersJPanel) component;
        manageCustomersJPanel.populateCustomerListTable();

        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
       
    }//GEN-LAST:event_btnBack0ActionPerformed

    private void btnCustomerChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerChangesActionPerformed
        // TODO add your handling code here:
        String custID = txtCustomerID.getText();
        String custName = txtCustomerName.getText();
        String custContact = txtCustomerContact.getText();
        String custAddr = txtCustomerAddress.getText();
        boolean allSet = true;
        
        if( custName.isEmpty() || custContact.isEmpty() || custAddr.isEmpty()  ) {
            allSet = false;
            JOptionPane.showMessageDialog(null, "Kindly Enter all the required fields!");
        }   else if (!system.validateMobileNo(custContact)) {
            allSet = false;
            JOptionPane.showMessageDialog(null, "Kindly enter a Valid Contact Number.");
        
        }
        if (!customerDirectory.isContactNoUnique(custContact)) {
            if(!currentPhoneNo.equals(custContact)){
                 allSet = false;
                JOptionPane.showMessageDialog(null, "Entered Contact No is already mapped to another Customer.");
            }
        }
        if(allSet == true){
            customerDirectory.updateCustomer(custID, custName, custContact, custAddr);
            JOptionPane.showMessageDialog(null, "Customer details updated!");
            disableEdit();
        }
    }//GEN-LAST:event_btnCustomerChangesActionPerformed

    private void btnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerActionPerformed
        // TODO add your handling code here:
    txtCustomerAddress.setEditable(true);
    txtCustomerContact.setEditable(true);
    txtCustomerName.setEditable(true);
    btnUpdateCustomer.setEnabled(false);
    }//GEN-LAST:event_btnUpdateCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack0;
    private javax.swing.JButton btnCustomerChanges;
    private javax.swing.JButton btnUpdateCustomer;
    private javax.swing.JLabel lblCustAddr;
    private javax.swing.JLabel lblCustContact;
    private javax.swing.JLabel lblCustID;
    private javax.swing.JLabel lblCustName;
    private javax.swing.JLabel lblViewUpdateCust;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerContact;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtCustomerName;
    // End of variables declaration//GEN-END:variables
}
