/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManRole;

import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManStore;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.DeliverManRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author juile
 */
public class AddDeliveryManJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDeliveryManJPanel
     */
    private final DeliveryManStore deliveryManDirectory;
    private final EcoSystem system;
    private final JPanel container;
    public AddDeliveryManJPanel(JPanel container, EcoSystem system, DeliveryManStore deliveryManDirectory) {
        initComponents();
        this.deliveryManDirectory = deliveryManDirectory;
        this.system = system;
        this.container = container;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDeliName = new javax.swing.JLabel();
        lblDeliUserName = new javax.swing.JLabel();
        lblDeliPass = new javax.swing.JLabel();
        lblDeliContact = new javax.swing.JLabel();
        txtDeliveryName = new javax.swing.JTextField();
        txtDeliveryUserName = new javax.swing.JTextField();
        pwDeliveryPassword = new javax.swing.JPasswordField();
        txtDeliveryContact = new javax.swing.JTextField();
        lblAddRest = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        btnAddDelivery = new javax.swing.JButton();
        pbDeliPassStr = new javax.swing.JProgressBar();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDeliName.setBackground(new java.awt.Color(204, 255, 255));
        lblDeliName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDeliName.setForeground(new java.awt.Color(0, 51, 51));
        lblDeliName.setText("Name:");
        add(lblDeliName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        lblDeliUserName.setBackground(new java.awt.Color(204, 255, 255));
        lblDeliUserName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDeliUserName.setForeground(new java.awt.Color(0, 51, 51));
        lblDeliUserName.setText("Set Username :");
        add(lblDeliUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        lblDeliPass.setBackground(new java.awt.Color(204, 255, 255));
        lblDeliPass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDeliPass.setForeground(new java.awt.Color(0, 51, 51));
        lblDeliPass.setText("Set Password :");
        add(lblDeliPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        lblDeliContact.setBackground(new java.awt.Color(204, 255, 255));
        lblDeliContact.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDeliContact.setForeground(new java.awt.Color(0, 51, 51));
        lblDeliContact.setText("Contact No:");
        add(lblDeliContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        txtDeliveryName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtDeliveryName.setForeground(new java.awt.Color(0, 51, 51));
        txtDeliveryName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(txtDeliveryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 53, 350, -1));

        txtDeliveryUserName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtDeliveryUserName.setForeground(new java.awt.Color(0, 51, 51));
        txtDeliveryUserName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(txtDeliveryUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 82, 350, -1));

        pwDeliveryPassword.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pwDeliveryPassword.setForeground(new java.awt.Color(0, 51, 51));
        pwDeliveryPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pwDeliveryPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwDeliveryPasswordActionPerformed(evt);
            }
        });
        pwDeliveryPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwDeliveryPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwDeliveryPasswordKeyTyped(evt);
            }
        });
        add(pwDeliveryPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 111, 350, -1));

        txtDeliveryContact.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtDeliveryContact.setForeground(new java.awt.Color(0, 51, 51));
        txtDeliveryContact.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(txtDeliveryContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 158, 350, -1));

        lblAddRest.setBackground(new java.awt.Color(204, 255, 255));
        lblAddRest.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAddRest.setForeground(new java.awt.Color(0, 51, 51));
        lblAddRest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddRest.setText("Delivery Person Information");
        add(lblAddRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        btnBack1.setBackground(new java.awt.Color(204, 255, 255));
        btnBack1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(0, 51, 51));
        btnBack1.setText("Back");
        btnBack1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 80, 30));

        btnAddDelivery.setBackground(new java.awt.Color(204, 255, 255));
        btnAddDelivery.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnAddDelivery.setForeground(new java.awt.Color(0, 51, 51));
        btnAddDelivery.setText("Add");
        btnAddDelivery.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDeliveryActionPerformed(evt);
            }
        });
        add(btnAddDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 80, 30));

        pbDeliPassStr.setBackground(new java.awt.Color(204, 255, 255));
        pbDeliPassStr.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        pbDeliPassStr.setForeground(new java.awt.Color(0, 51, 51));
        pbDeliPassStr.setMaximum(30);
        pbDeliPassStr.setMinimum(1);
        pbDeliPassStr.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pbDeliPassStrStateChanged(evt);
            }
        });
        add(pbDeliPassStr, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 139, 126, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void pwDeliveryPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwDeliveryPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwDeliveryPasswordActionPerformed

    private void pwDeliveryPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwDeliveryPasswordKeyReleased
        // TODO add your handling code here
    }//GEN-LAST:event_pwDeliveryPasswordKeyReleased

    private void pwDeliveryPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwDeliveryPasswordKeyTyped
        // TODO add your handling code here:
        int pwSize = pwDeliveryPassword.getText().length();
        pbDeliPassStr.setValue(pwSize);
    }//GEN-LAST:event_pwDeliveryPasswordKeyTyped

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageDeliveryManJPanel manageDeliJPanel = (ManageDeliveryManJPanel) component;
        manageDeliJPanel.populateDeliveryManTable();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnAddDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDeliveryActionPerformed
        // TODO add your handling code here:

        String custName = txtDeliveryName.getText();
        String custContact = txtDeliveryContact.getText();
        String custUserName = txtDeliveryUserName.getText();
        String custPass = String.valueOf(pwDeliveryPassword.getPassword());

        if( custName.isEmpty() || custContact.isEmpty() || 
            custUserName.isEmpty() || custPass.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Kindly Enter all the required fields!");
        }   else if (!system.validateMobileNo(custContact)) {
            JOptionPane.showMessageDialog(null, "Kindly enter a Valid Contact Number.");
        }     else if (!system.getUserAccountDirectory().checkIfUsernameIsUnique(custUserName)) {
            JOptionPane.showMessageDialog(null, "Entered User Name is already mapped to another Restaurant");
        }     else if (!deliveryManDirectory.isContactNoUnique(custContact)) {
            JOptionPane.showMessageDialog(null, "Entered Contact No is already mapped to another Restaurant.");
        }   else {
            DeliveryMan deliveryMan = new DeliveryMan();
            deliveryMan.setDeliName(custName);
            deliveryMan.setDeliPhoneNo(custContact);
            deliveryManDirectory.addDeliveryMan(deliveryMan);
            Employee employee = system.getEmployeeDirectory().createEmployee(deliveryMan.getDeliveryID());
            system.setDeliveryManDirectory(deliveryManDirectory);
            UserAccount account = system.getUserAccountDirectory().createUserAccount(custUserName, custPass, employee, new DeliverManRole());
            JOptionPane.showMessageDialog(null, "New Delivery Man "+account.getUsername()+" added to the System Successfully!");
            resetFields();
        }
    }//GEN-LAST:event_btnAddDeliveryActionPerformed
    public void resetFields(){
            txtDeliveryName.setText("");
            txtDeliveryContact.setText("");
            txtDeliveryUserName.setText("");
            pwDeliveryPassword.setText("");
    }
    private void pbDeliPassStrStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pbDeliPassStrStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_pbDeliPassStrStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDelivery;
    private javax.swing.JButton btnBack1;
    private javax.swing.JLabel lblAddRest;
    private javax.swing.JLabel lblDeliContact;
    private javax.swing.JLabel lblDeliName;
    private javax.swing.JLabel lblDeliPass;
    private javax.swing.JLabel lblDeliUserName;
    private javax.swing.JProgressBar pbDeliPassStr;
    private javax.swing.JPasswordField pwDeliveryPassword;
    private javax.swing.JTextField txtDeliveryContact;
    private javax.swing.JTextField txtDeliveryName;
    private javax.swing.JTextField txtDeliveryUserName;
    // End of variables declaration//GEN-END:variables
}
