/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManRole;

import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManStore;
import Business.EcoSystem;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author juile
 */
public class ViewUpdateDeliveryManJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewUpdateDeliveryManJPanel
     */
    public JPanel container;
    public DeliveryMan deliveryMan;
    public DeliveryManStore deliveryManDirectory;
    private final EcoSystem system;
    private String currentPhoneNo;
    
    
    public ViewUpdateDeliveryManJPanel(EcoSystem system, JPanel container, DeliveryMan deliveryMan, DeliveryManStore deliveryManDirectory) {
        initComponents();
        this.container = container;
        this.deliveryMan = deliveryMan;
        this.deliveryManDirectory = deliveryManDirectory;
        this.system = system;
        this.currentPhoneNo = deliveryMan.getDeliPhoneNo();
        
        txtDeliveryUsername.setText(deliveryMan.getDeliveryID());
        txtDeliveryName.setText(deliveryMan.getDeliName());
        txtDeliveryContact.setText(deliveryMan.getDeliPhoneNo());
        disableEdit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDeliContact = new javax.swing.JLabel();
        txtDeliveryContact = new javax.swing.JTextField();
        txtDeliveryName = new javax.swing.JTextField();
        txtDeliveryUsername = new javax.swing.JTextField();
        lblDeliName = new javax.swing.JLabel();
        lblDeliNo = new javax.swing.JLabel();
        lblAddDeli = new javax.swing.JLabel();
        btnBack3 = new javax.swing.JButton();
        btnDeliveryUpdate = new javax.swing.JButton();
        btnDeliverySave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        lblDeliContact.setBackground(new java.awt.Color(204, 255, 255));
        lblDeliContact.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDeliContact.setForeground(new java.awt.Color(0, 51, 51));
        lblDeliContact.setText("Contact No :");

        txtDeliveryContact.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtDeliveryContact.setForeground(new java.awt.Color(0, 51, 51));
        txtDeliveryContact.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtDeliveryName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtDeliveryName.setForeground(new java.awt.Color(0, 51, 51));
        txtDeliveryName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtDeliveryUsername.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtDeliveryUsername.setForeground(new java.awt.Color(0, 51, 51));
        txtDeliveryUsername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblDeliName.setBackground(new java.awt.Color(204, 255, 255));
        lblDeliName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDeliName.setForeground(new java.awt.Color(0, 51, 51));
        lblDeliName.setText("Name:");

        lblDeliNo.setBackground(new java.awt.Color(204, 255, 255));
        lblDeliNo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDeliNo.setForeground(new java.awt.Color(0, 51, 51));
        lblDeliNo.setText("Username :");

        lblAddDeli.setBackground(new java.awt.Color(204, 255, 255));
        lblAddDeli.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAddDeli.setForeground(new java.awt.Color(0, 51, 51));
        lblAddDeli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddDeli.setText("Create Delivery Person");

        btnBack3.setBackground(new java.awt.Color(204, 255, 255));
        btnBack3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnBack3.setForeground(new java.awt.Color(0, 51, 51));
        btnBack3.setText("Back");
        btnBack3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });

        btnDeliveryUpdate.setBackground(new java.awt.Color(204, 255, 255));
        btnDeliveryUpdate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnDeliveryUpdate.setForeground(new java.awt.Color(0, 51, 51));
        btnDeliveryUpdate.setText(" Update");
        btnDeliveryUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeliveryUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryUpdateActionPerformed(evt);
            }
        });

        btnDeliverySave.setBackground(new java.awt.Color(204, 255, 255));
        btnDeliverySave.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnDeliverySave.setForeground(new java.awt.Color(0, 51, 51));
        btnDeliverySave.setText("Save");
        btnDeliverySave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeliverySave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliverySaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(lblAddDeli))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDeliName)
                            .addComponent(lblDeliContact)
                            .addComponent(lblDeliNo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDeliveryName)
                            .addComponent(txtDeliveryContact)
                            .addComponent(txtDeliveryUsername)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDeliverySave, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                                .addComponent(btnDeliveryUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)
                                .addComponent(btnBack3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblAddDeli)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliNo)
                    .addComponent(txtDeliveryUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliName)
                    .addComponent(txtDeliveryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDeliveryContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeliveryUpdate)
                            .addComponent(btnBack3)
                            .addComponent(btnDeliverySave)))
                    .addComponent(lblDeliContact))
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageDeliveryManJPanel manageDeliJPanel = (ManageDeliveryManJPanel) component;
        manageDeliJPanel.populateDeliveryManTable();

        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);

    }//GEN-LAST:event_btnBack3ActionPerformed
    public void disableEdit() {
        txtDeliveryUsername.setEditable(false);
        txtDeliveryName.setEditable(false);
        txtDeliveryContact.setEditable(false);
    }
    private void btnDeliveryUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryUpdateActionPerformed
        // TODO add your handling code here:
        txtDeliveryName.setEditable(true);
        txtDeliveryContact.setEditable(true);
     
        btnDeliveryUpdate.setEnabled(false);
    }//GEN-LAST:event_btnDeliveryUpdateActionPerformed

    private void btnDeliverySaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliverySaveActionPerformed
        // TODO add your handling code here:
        String custID = txtDeliveryUsername.getText();
        String custName = txtDeliveryName.getText();
        String custContact = txtDeliveryContact.getText();
        boolean allSet = true;

        if( custName.isEmpty() || custContact.isEmpty()  ) {
            allSet = false;
            JOptionPane.showMessageDialog(null, "Kindly Enter all the required fields!");
        }   else if (!system.validateMobileNo(custContact)) {
            allSet = false;
            JOptionPane.showMessageDialog(null, "Kindly enter a Valid Contact Number.");
        }   
        
        if (!deliveryManDirectory.isContactNoUnique(custContact)) {
            if(!currentPhoneNo.equals(custContact)){
                allSet = false;
                JOptionPane.showMessageDialog(null, "Entered Contact No is already mapped to another Customer.");
            }
        }
        if(allSet == true){
            deliveryManDirectory.updateDeliveryMan(custID, custName, custContact);
            JOptionPane.showMessageDialog(null, "Customer details updated!");
            disableEdit();
        }
    }//GEN-LAST:event_btnDeliverySaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnDeliverySave;
    private javax.swing.JButton btnDeliveryUpdate;
    private javax.swing.JLabel lblAddDeli;
    private javax.swing.JLabel lblDeliContact;
    private javax.swing.JLabel lblDeliName;
    private javax.swing.JLabel lblDeliNo;
    private javax.swing.JTextField txtDeliveryContact;
    private javax.swing.JTextField txtDeliveryName;
    private javax.swing.JTextField txtDeliveryUsername;
    // End of variables declaration//GEN-END:variables
}
