/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Customer.Customer;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.AdminRole;
import Business.Role.CustomerRole;
import Business.Role.DeliveryManRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vini
 */
public class SystemAdminUpdateCustomer extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminUpdateCustomer
     */
    private JPanel userProcessContainerSAUC;
    private EcoSystem ecosystemSAUC;
    private Customer customerSAUC;
    
    public SystemAdminUpdateCustomer(JPanel userProcessContainer, Customer customer, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainerSAUC = userProcessContainer;
        this.customerSAUC = customer;
        this.ecosystemSAUC = ecosystem;
        txtNameSAUC.setText(customer.getCustomerName());
        txtPhoneSAUC.setText(customer.getPhone());
        txtAddressSAUC.setText(customer.getAddress());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBackSAUC = new javax.swing.JButton();
        btnSubmitSAUC = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNameSAUC = new javax.swing.JTextField();
        txtPhoneSAUC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAddressSAUC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        btnBackSAUC.setBackground(new java.awt.Color(255, 255, 255));
        btnBackSAUC.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnBackSAUC.setText("< Back");
        btnBackSAUC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBackSAUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackSAUCActionPerformed(evt);
            }
        });
        add(btnBackSAUC);
        btnBackSAUC.setBounds(26, 24, 43, 21);

        btnSubmitSAUC.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmitSAUC.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSubmitSAUC.setText("Submit");
        btnSubmitSAUC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitSAUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitSAUCActionPerformed(evt);
            }
        });
        add(btnSubmitSAUC);
        btnSubmitSAUC.setBounds(255, 191, 160, 39);

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Update Customer");
        add(lblTitle);
        lblTitle.setBounds(90, 10, 350, 29);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Name:");
        add(jLabel4);
        jLabel4.setBounds(65, 90, 144, 14);

        txtNameSAUC.setEditable(false);
        txtNameSAUC.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNameSAUC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtNameSAUC);
        txtNameSAUC.setBounds(255, 89, 160, 16);

        txtPhoneSAUC.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtPhoneSAUC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtPhoneSAUC);
        txtPhoneSAUC.setBounds(255, 123, 160, 16);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Phone Number:");
        add(jLabel5);
        jLabel5.setBounds(65, 124, 144, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Address:");
        add(jLabel6);
        jLabel6.setBounds(65, 158, 144, 14);

        txtAddressSAUC.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtAddressSAUC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtAddressSAUC);
        txtAddressSAUC.setBounds(255, 157, 160, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Update_Customer.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 80, 570, 350);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackSAUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackSAUCActionPerformed
        // TODO add your handling code here:
        userProcessContainerSAUC.remove(this);
        CardLayout layout = (CardLayout) userProcessContainerSAUC.getLayout();
        layout.previous(userProcessContainerSAUC);
    }//GEN-LAST:event_btnBackSAUCActionPerformed

    private void btnSubmitSAUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitSAUCActionPerformed
        // TODO add your handling code here:
        if(validateThisSAUC())
        {
            customerSAUC.setAddress(txtAddressSAUC.getText());
            customerSAUC.setPhone(txtPhoneSAUC.getText());
            JOptionPane.showMessageDialog(null, "Details for " + customerSAUC.getCustomerName()+ " updated successfully!");
        }
        else
        {
            return;
        }
    }//GEN-LAST:event_btnSubmitSAUCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackSAUC;
    private javax.swing.JButton btnSubmitSAUC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAddressSAUC;
    private javax.swing.JTextField txtNameSAUC;
    private javax.swing.JTextField txtPhoneSAUC;
    // End of variables declaration//GEN-END:variables

    private boolean validateThisSAUC() {
        String regex = "\\d{10}";
        if(("".equals(txtPhoneSAUC.getText())) || ("".equals(txtAddressSAUC.getText())))
        {
            JOptionPane.showMessageDialog(null,"Please fill all details!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else if(!(txtPhoneSAUC.getText().matches(regex)))
        {
            JOptionPane.showMessageDialog(null,"Phone number must have only 10 digits!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else
        {
            return true;
        }
    }
}
