/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Pharmacy.Pharmacy;
import Business.Role.AdminRole;

import Business.Role.DeliveryManRole;
import Business.SupplierEmp.SupplierEmp;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vini
 */
public class SystemManageEmployees extends javax.swing.JPanel {

    /**
     * Creates new form SystemManageEmployees
     */
    private JPanel userProcessContainer;
    private Pharmacy pharmacy;
    private EcoSystem ecosystem;
    public SystemManageEmployees(JPanel userProcessContainer, Pharmacy pharmacy, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pharmacy = pharmacy;
        this.ecosystem = ecosystem;
        txtUsernameSME.setEnabled(false);
        txtPasswordSME.setEnabled(false);
        txtRePasswordSME.setEnabled(false);
        txtNameSME.setEnabled(false);
        txtPhoneSME.setEnabled(false);
        txtAddressSME.setEnabled(false);
        btnSubmitSME.setEnabled(false);
        btnDeleteSME.setEnabled(false);
        btnManageSME.setEnabled(false);
        radioBtnDeliverySME.setEnabled(false);
        radioBtnManagerSME.setEnabled(false);
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        txtRePasswordSME = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAddressSME = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radioBtnManagerSME = new javax.swing.JRadioButton();
        btnBackSME = new javax.swing.JButton();
        btnSubmitSME = new javax.swing.JButton();
        radioBtnDeliverySME = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfileSME = new javax.swing.JTable();
        btnManageSME = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnDeleteSME = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnNewEmployeeSME = new javax.swing.JButton();
        txtNameSME = new javax.swing.JTextField();
        txtUsernameSME = new javax.swing.JTextField();
        txtPhoneSME = new javax.swing.JTextField();
        txtPasswordSME = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Phone Number:");
        add(jLabel5);
        jLabel5.setBounds(170, 334, 144, 14);

        txtRePasswordSME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtRePasswordSME);
        txtRePasswordSME.setBounds(318, 261, 200, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Address:");
        add(jLabel6);
        jLabel6.setBounds(170, 378, 144, 14);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Username: ");
        add(jLabel1);
        jLabel1.setBounds(170, 193, 144, 25);

        txtAddressSME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtAddressSME);
        txtAddressSME.setBounds(318, 375, 200, 22);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Password: ");
        add(jLabel2);
        jLabel2.setBounds(170, 230, 144, 25);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Role:");
        add(jLabel7);
        jLabel7.setBounds(170, 412, 144, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Confirm Password:");
        add(jLabel3);
        jLabel3.setBounds(170, 261, 144, 27);

        buttonGroup1.add(radioBtnManagerSME);
        radioBtnManagerSME.setText("Pharmacy Manager");
        radioBtnManagerSME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnManagerSMEActionPerformed(evt);
            }
        });
        add(radioBtnManagerSME);
        radioBtnManagerSME.setBounds(318, 419, 200, 19);

        btnBackSME.setBackground(new java.awt.Color(255, 255, 255));
        btnBackSME.setText("< Back");
        btnBackSME.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBackSME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackSMEActionPerformed(evt);
            }
        });
        add(btnBackSME);
        btnBackSME.setBounds(10, 249, 55, 27);

        btnSubmitSME.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmitSME.setText("Submit");
        btnSubmitSME.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitSME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitSMEActionPerformed(evt);
            }
        });
        add(btnSubmitSME);
        btnSubmitSME.setBounds(318, 503, 200, 44);

        buttonGroup1.add(radioBtnDeliverySME);
        radioBtnDeliverySME.setText("Delivery Man");
        radioBtnDeliverySME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnDeliverySMEActionPerformed(evt);
            }
        });
        add(radioBtnDeliverySME);
        radioBtnDeliverySME.setBounds(318, 456, 200, 29);

        tblProfileSME.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee No.", "Employee Name", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProfileSME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProfileSMEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProfileSME);

        add(jScrollPane1);
        jScrollPane1.setBounds(170, 84, 740, 97);

        btnManageSME.setBackground(new java.awt.Color(255, 255, 255));
        btnManageSME.setText("View Employee ");
        btnManageSME.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageSME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSMEActionPerformed(evt);
            }
        });
        add(btnManageSME);
        btnManageSME.setBounds(10, 84, 131, 42);

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Employees");
        add(lblTitle);
        lblTitle.setBounds(101, 18, 445, 29);

        btnDeleteSME.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteSME.setText("Delete Employee");
        btnDeleteSME.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeleteSME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSMEActionPerformed(evt);
            }
        });
        add(btnDeleteSME);
        btnDeleteSME.setBounds(10, 137, 131, 44);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Name:");
        add(jLabel4);
        jLabel4.setBounds(170, 297, 144, 14);

        btnNewEmployeeSME.setBackground(new java.awt.Color(255, 255, 255));
        btnNewEmployeeSME.setText("Create Employee ");
        btnNewEmployeeSME.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNewEmployeeSME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewEmployeeSMEActionPerformed(evt);
            }
        });
        add(btnNewEmployeeSME);
        btnNewEmployeeSME.setBounds(10, 192, 131, 46);

        txtNameSME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtNameSME);
        txtNameSME.setBounds(318, 294, 200, 22);

        txtUsernameSME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtUsernameSME);
        txtUsernameSME.setBounds(318, 192, 200, 25);

        txtPhoneSME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtPhoneSME);
        txtPhoneSME.setBounds(318, 331, 200, 22);

        txtPasswordSME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtPasswordSME);
        txtPasswordSME.setBounds(318, 229, 200, 22);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Manage_Emplyee_Final_IMAGE.png"))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(0, 0, 1230, 780);
    }// </editor-fold>//GEN-END:initComponents

    private void radioBtnManagerSMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnManagerSMEActionPerformed
        // TODO add your handling code here:
        radioBtnDeliverySME.setSelected(false);
    }//GEN-LAST:event_radioBtnManagerSMEActionPerformed

    private void btnBackSMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackSMEActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackSMEActionPerformed

    private void btnSubmitSMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitSMEActionPerformed
        // TODO add your handling code here:
        if(validateThis())
        {
                       // SupplierEmp se = ecosystem.getSupplierEmpDirectory().createSupplierEmp(txtNameSME.getText(), txtAddressSME.getText(), txtPhoneSME.getText());

            Employee e = pharmacy.getEmployeeDirectory().createEmployee(txtNameSME.getText(), txtAddressSME.getText(), txtPhoneSME.getText());
            if(e == null)
            {
                JOptionPane.showMessageDialog(null,"Employee " + txtNameSME.getText() + " already exists!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            else
            {
                if(radioBtnManagerSME.isSelected())
                {
                    UserAccount ua = ecosystem.getUserAccountDirectory().createUserAccount(txtUsernameSME.getText(), txtPasswordSME.getText(), e, new AdminRole());
                    if(ua != null)
                    {
                        JOptionPane.showMessageDialog(null, "Manager account created successfully for " + e.getName());
                    }
                    else
                    {
                        pharmacy.getEmployeeDirectory().deleteEmployee(e);
                        JOptionPane.showMessageDialog(null,"Username " + txtUsernameSME.getText() + " already exists!", "Warning", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
                else
                {
                    UserAccount ua = ecosystem.getUserAccountDirectory().createUserAccount(txtUsernameSME.getText(), txtPasswordSME.getText(), e, new DeliveryManRole());
                    if(ua != null)
                    {
                        DeliveryMan dm = pharmacy.getDeliveryManDirectory().createDeliveryMan(txtNameSME.getText(), txtAddressSME.getText(), txtPhoneSME.getText());
                        JOptionPane.showMessageDialog(null, "Delivery Man account created successfully for " + e.getName());
                    }
                    else
                    {
                        pharmacy.getEmployeeDirectory().deleteEmployee(e);
                        JOptionPane.showMessageDialog(null,"Username " + txtUsernameSME.getText() + " already exists!", "Warning", JOptionPane.WARNING_MESSAGE);
                        return;
                    }

                }
                btnNewEmployeeSME.setEnabled(true);
                txtUsernameSME.setText("");
                txtUsernameSME.setEnabled(false);
                txtPasswordSME.setText("");
                txtPasswordSME.setEnabled(false);
                txtRePasswordSME.setText("");
                txtRePasswordSME.setEnabled(false);
                txtNameSME.setText("");
                txtNameSME.setEnabled(false);
                txtPhoneSME.setText("");
                txtPhoneSME.setEnabled(false);
                txtAddressSME.setText("");
                txtAddressSME.setEnabled(false);
                btnSubmitSME.setEnabled(false);
                radioBtnDeliverySME.setSelected(false);
                radioBtnDeliverySME.setEnabled(false);
                radioBtnManagerSME.setSelected(false);
                radioBtnManagerSME.setEnabled(false);
            }
            populateTable();
        }
        else
        {
            return;
        }
    }//GEN-LAST:event_btnSubmitSMEActionPerformed

    private void radioBtnDeliverySMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnDeliverySMEActionPerformed
        // TODO add your handling code here:
        radioBtnManagerSME.setSelected(false);
    }//GEN-LAST:event_radioBtnDeliverySMEActionPerformed

    private void tblProfileSMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProfileSMEMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblProfileSME.getSelectedRow();
        if (selectedRow >= 0)
        {
            btnDeleteSME.setEnabled(true);
            btnManageSME.setEnabled(true);
        }
    }//GEN-LAST:event_tblProfileSMEMouseClicked

    private void btnManageSMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSMEActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblProfileSME.getSelectedRow();
        if (selectedRow >= 0)
        {
            Employee selectedEmployee = (Employee) tblProfileSME.getValueAt(selectedRow, 1);
            SystemUpdateEmployee fs = new SystemUpdateEmployee(userProcessContainer, selectedEmployee, ecosystem);
            userProcessContainer.add("SysAdminUpdateEmployees", fs);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please select a row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnManageSMEActionPerformed

    private void btnDeleteSMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSMEActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblProfileSME.getSelectedRow();
        if (selectedRow >= 0)
        {
            Employee selectedEmployee = (Employee) tblProfileSME.getValueAt(selectedRow, 1);
            pharmacy.getEmployeeDirectory().deleteEmployee(selectedEmployee);
            JOptionPane.showMessageDialog(null, "Employee " + selectedEmployee.getName()+ " deleted successfully!");
            populateTable();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please select a row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnDeleteSMEActionPerformed

    private void btnNewEmployeeSMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewEmployeeSMEActionPerformed
        // TODO add your handling code here:
        btnNewEmployeeSME.setEnabled(false);
        txtUsernameSME.setEnabled(true);
        txtPasswordSME.setEnabled(true);
        txtRePasswordSME.setEnabled(true);
        txtNameSME.setEnabled(true);
        txtPhoneSME.setEnabled(true);
        txtAddressSME.setEnabled(true);
        btnSubmitSME.setEnabled(true);
        radioBtnDeliverySME.setEnabled(true);
        radioBtnManagerSME.setEnabled(true);
    }//GEN-LAST:event_btnNewEmployeeSMEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackSME;
    private javax.swing.JButton btnDeleteSME;
    private javax.swing.JButton btnManageSME;
    private javax.swing.JButton btnNewEmployeeSME;
    private javax.swing.JButton btnSubmitSME;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton radioBtnDeliverySME;
    private javax.swing.JRadioButton radioBtnManagerSME;
    private javax.swing.JTable tblProfileSME;
    private javax.swing.JTextField txtAddressSME;
    private javax.swing.JTextField txtNameSME;
    private javax.swing.JTextField txtPasswordSME;
    private javax.swing.JTextField txtPhoneSME;
    private javax.swing.JTextField txtRePasswordSME;
    private javax.swing.JTextField txtUsernameSME;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel)tblProfileSME.getModel();
        dtm.setRowCount(0);
        if(pharmacy.getEmployeeDirectory().getEmployeeList() != null)
        {
            for(Employee e : pharmacy.getEmployeeDirectory().getEmployeeList())
            {
                Object[] row = new Object[dtm.getColumnCount()];
                row[0]= e.getId();
                row[1]= e;
                UserAccount ua = ecosystem.getUserAccountDirectory().findEmployee(e);
                row[2] = ua.getRole().toString().substring(14).replace("Role", "");
                dtm.addRow(row);
            }
        }
        if(dtm.getRowCount() == 0)
            {
                btnDeleteSME.setEnabled(false);
                btnManageSME.setEnabled(false);
            }
    }

    private boolean validateThis() {
        String regex = "\\d{10}";
        if(("".equals(txtUsernameSME.getText())) || ("".equals(txtPasswordSME.getText())) || ("".equals(txtRePasswordSME.getText())) 
                || ("".equals(txtNameSME.getText())) || ("".equals(txtPhoneSME.getText())) || ("".equals(txtAddressSME.getText()))
                || ((radioBtnDeliverySME.isEnabled() == false) && (radioBtnManagerSME.isEnabled() == false)))
        {
            JOptionPane.showMessageDialog(null,"Please fill all details!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else if(!(txtPasswordSME.getText().equals(txtRePasswordSME.getText())))
        {
            JOptionPane.showMessageDialog(null,"Passwords do not match!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else if(!(txtPhoneSME.getText().matches(regex)))
        {
            JOptionPane.showMessageDialog(null,"Phone number must have only 10 digits!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else
        {
            return true;
        }
    }
}
