/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.AdminRole;

import Business.Role.DeliveryManRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class SystemUpdateEmployee extends javax.swing.JPanel {

    /**
     * Creates new form SystemUpdateEmployee
     */
    private JPanel userProcessContainerSUE;
    private Employee employeeSUE;
    private EcoSystem ecosystemSUE;
    private UserAccount userSUE;
    
    public SystemUpdateEmployee(JPanel userProcessContainer, Employee employee, EcoSystem system) {
        initComponents();
        this.userProcessContainerSUE = userProcessContainer;
        this.employeeSUE = employee;
        this.ecosystemSUE = system;
        this.userSUE = ecosystemSUE.getUserAccountDirectory().findEmployee(employee);
        txtUsernameSUE.setText(userSUE.getUsername());
        txtPasswordSUE.setText(userSUE.getPassword());
        txtRePasswordSUE.setText(userSUE.getPassword());
        txtNameSUE.setText(employee.getName());
        txtPhoneSUE.setText(employee.getPhone());
        txtAddressSUE.setText(employee.getAddress());
        if(this.userSUE.getRole().toString().equals("Business.Role.DeliverManRole"))
        {
            radioBtnDeliverySUE.setSelected(true);
        }
        else
        {
            radioBtnManagerSUE.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNameSUE = new javax.swing.JTextField();
        btnBackSUE = new javax.swing.JButton();
        txtPhoneSUE = new javax.swing.JTextField();
        txtUsernameSUE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPasswordSUE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRePasswordSUE = new javax.swing.JTextField();
        txtAddressSUE = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radioBtnManagerSUE = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        radioBtnDeliverySUE = new javax.swing.JRadioButton();
        btnSubmitSUE = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Update Employees");
        add(lblTitle);
        lblTitle.setBounds(98, 29, 266, 24);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Name:");
        add(jLabel4);
        jLabel4.setBounds(19, 214, 144, 14);

        txtNameSUE.setEditable(false);
        txtNameSUE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtNameSUE);
        txtNameSUE.setBounds(209, 208, 160, 22);

        btnBackSUE.setBackground(new java.awt.Color(255, 255, 255));
        btnBackSUE.setText("< Back");
        btnBackSUE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBackSUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackSUEActionPerformed(evt);
            }
        });
        add(btnBackSUE);
        btnBackSUE.setBounds(136, 404, 55, 27);

        txtPhoneSUE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtPhoneSUE);
        txtPhoneSUE.setBounds(209, 248, 160, 22);

        txtUsernameSUE.setEditable(false);
        txtUsernameSUE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtUsernameSUE);
        txtUsernameSUE.setBounds(209, 79, 160, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Phone Number:");
        add(jLabel5);
        jLabel5.setBounds(19, 254, 144, 14);

        txtPasswordSUE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtPasswordSUE);
        txtPasswordSUE.setBounds(209, 128, 160, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Address:");
        add(jLabel6);
        jLabel6.setBounds(19, 294, 144, 14);

        txtRePasswordSUE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtRePasswordSUE);
        txtRePasswordSUE.setBounds(209, 168, 160, 22);

        txtAddressSUE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtAddressSUE);
        txtAddressSUE.setBounds(209, 288, 160, 22);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Username: ");
        add(jLabel1);
        jLabel1.setBounds(19, 85, 144, 14);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Role:");
        add(jLabel7);
        jLabel7.setBounds(19, 337, 144, 14);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Password: ");
        add(jLabel2);
        jLabel2.setBounds(19, 134, 144, 14);

        buttonGroup1.add(radioBtnManagerSUE);
        radioBtnManagerSUE.setText("Pharmacy Manager");
        radioBtnManagerSUE.setEnabled(false);
        add(radioBtnManagerSUE);
        radioBtnManagerSUE.setBounds(209, 328, 160, 29);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Confirm Password:");
        add(jLabel3);
        jLabel3.setBounds(19, 174, 144, 14);

        buttonGroup1.add(radioBtnDeliverySUE);
        radioBtnDeliverySUE.setText("Delivery Man");
        radioBtnDeliverySUE.setEnabled(false);
        add(radioBtnDeliverySUE);
        radioBtnDeliverySUE.setBounds(209, 357, 160, 29);

        btnSubmitSUE.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmitSUE.setText("Submit");
        btnSubmitSUE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitSUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitSUEActionPerformed(evt);
            }
        });
        add(btnSubmitSUE);
        btnSubmitSUE.setBounds(209, 404, 160, 27);
        add(jLabel8);
        jLabel8.setBounds(19, 11, 0, 99);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Manage_Emplyee_Final_IMAGE.png"))); // NOI18N
        add(jLabel9);
        jLabel9.setBounds(0, 0, 1230, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackSUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackSUEActionPerformed
        // TODO add your handling code here:
        userProcessContainerSUE.remove(this);
        CardLayout layout = (CardLayout) userProcessContainerSUE.getLayout();
        layout.previous(userProcessContainerSUE);
    }//GEN-LAST:event_btnBackSUEActionPerformed

    private void btnSubmitSUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitSUEActionPerformed
        // TODO add your handling code here:
        if(validateThisSUE())
        {
            userSUE.setPassword(txtPasswordSUE.getText());
            employeeSUE.setAddress(txtAddressSUE.getText());
            employeeSUE.setPhone((txtPhoneSUE.getText()));
            JOptionPane.showMessageDialog(null, "Details for " + employeeSUE.getName()+ " updated successfully!");
        }
        else
        {
            return;
        }
    }//GEN-LAST:event_btnSubmitSUEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackSUE;
    private javax.swing.JButton btnSubmitSUE;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton radioBtnDeliverySUE;
    private javax.swing.JRadioButton radioBtnManagerSUE;
    private javax.swing.JTextField txtAddressSUE;
    private javax.swing.JTextField txtNameSUE;
    private javax.swing.JTextField txtPasswordSUE;
    private javax.swing.JTextField txtPhoneSUE;
    private javax.swing.JTextField txtRePasswordSUE;
    private javax.swing.JTextField txtUsernameSUE;
    // End of variables declaration//GEN-END:variables

    private boolean validateThisSUE() {
        String regex = "\\d{10}";
        if(("".equals(txtPasswordSUE.getText())) || ("".equals(txtRePasswordSUE.getText())) 
                || ("".equals(txtPhoneSUE.getText())) || ("".equals(txtAddressSUE.getText())))
        {
            JOptionPane.showMessageDialog(null,"Please fill all details!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else if(!(txtPasswordSUE.getText().equals(txtRePasswordSUE.getText())))
        {
            JOptionPane.showMessageDialog(null,"Passwords do not match!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else if(!(txtPhoneSUE.getText().matches(regex)))
        {
            JOptionPane.showMessageDialog(null,"Phone number must have only 10 digits!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else
        {
            return true;
        }
    }
}
