/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharmacyAdminRole;

import Business.DeliveryMan.DeliveryMan;
import Business.Orders.Orders;
import Business.Pharmacy.Pharmacy;
import java.awt.CardLayout;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dhrit
 */
public class AdminManageOrders extends javax.swing.JPanel {

    /**
     * Creates new form AdminManageOrders
     */
    JPanel userProcessContainer;
    Pharmacy pharmacy;
    public AdminManageOrders(JPanel userProcessContainer, Pharmacy pharmacy) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pharmacy = pharmacy;
        PharmacyAMOAssignDeliveryManButton.setEnabled(false);
        PharmacyAMOCombo.setEnabled(false);
       
        PharmacyAMOvalueLabel2.setText(pharmacy.getName());
        populateTable();
        PharmacyAMOCombo.addItem("");
        System.out.println(pharmacy.getDeliveryManDirectory().getDeliveryManList().size());
        for(DeliveryMan dm : pharmacy.getDeliveryManDirectory().getDeliveryManList())
        {
            System.out.println(dm.getName());
            PharmacyAMOCombo.addItem(dm.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PharmacyAMOAssignDeliveryManButton = new javax.swing.JButton();
        PharmacyAMOCurrentOrdersLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PharmacyTable2 = new javax.swing.JTable();
        PharmacyAMOvalueLabel2 = new javax.swing.JLabel();
        PharmacyAMOLabel2 = new javax.swing.JLabel();
        PharmacyAMODeleteButton = new javax.swing.JButton();
        PharmacyAMOBackButton2 = new javax.swing.JButton();
        PharmacyAMOCombo = new javax.swing.JComboBox<>();
        PharmacyAMOLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        PharmacyAMOAssignDeliveryManButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PharmacyAMOAssignDeliveryManButton.setText("Assign Delivery Man");
        PharmacyAMOAssignDeliveryManButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PharmacyAMOAssignDeliveryManButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PharmacyAMOAssignDeliveryManButtonActionPerformed(evt);
            }
        });
        add(PharmacyAMOAssignDeliveryManButton);
        PharmacyAMOAssignDeliveryManButton.setBounds(1138, 333, 210, 50);

        PharmacyAMOCurrentOrdersLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PharmacyAMOCurrentOrdersLabel.setText("Current Orders");
        add(PharmacyAMOCurrentOrdersLabel);
        PharmacyAMOCurrentOrdersLabel.setBounds(238, 87, 97, 17);

        PharmacyTable2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        PharmacyTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order No.", "Customer Name", "Order Date", "Delivery Man"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PharmacyTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PharmacyTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PharmacyTable2);

        add(jScrollPane1);
        jScrollPane1.setBounds(25, 122, 1430, 84);

        PharmacyAMOvalueLabel2.setBackground(new java.awt.Color(204, 204, 255));
        PharmacyAMOvalueLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PharmacyAMOvalueLabel2.setText("<value>");
        add(PharmacyAMOvalueLabel2);
        PharmacyAMOvalueLabel2.setBounds(308, 39, 282, 30);

        PharmacyAMOLabel2.setBackground(new java.awt.Color(204, 204, 255));
        PharmacyAMOLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PharmacyAMOLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        PharmacyAMOLabel2.setText("Pharmacy");
        add(PharmacyAMOLabel2);
        PharmacyAMOLabel2.setBounds(10, 39, 292, 30);

        PharmacyAMODeleteButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PharmacyAMODeleteButton.setText("Delete");
        PharmacyAMODeleteButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PharmacyAMODeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PharmacyAMODeleteButtonActionPerformed(evt);
            }
        });
        add(PharmacyAMODeleteButton);
        PharmacyAMODeleteButton.setBounds(1129, 223, 220, 50);

        PharmacyAMOBackButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PharmacyAMOBackButton2.setText("< Back");
        PharmacyAMOBackButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PharmacyAMOBackButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PharmacyAMOBackButton2ActionPerformed(evt);
            }
        });
        add(PharmacyAMOBackButton2);
        PharmacyAMOBackButton2.setBounds(25, 224, 100, 40);

        PharmacyAMOCombo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        add(PharmacyAMOCombo);
        PharmacyAMOCombo.setBounds(820, 280, 220, 60);

        PharmacyAMOLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/MicrosoftTeams-image (11).png"))); // NOI18N
        add(PharmacyAMOLabel);
        PharmacyAMOLabel.setBounds(0, 10, 1460, 770);
    }// </editor-fold>//GEN-END:initComponents

    private void PharmacyAMOAssignDeliveryManButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PharmacyAMOAssignDeliveryManButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = PharmacyTable2.getSelectedRow();
        if (selectedRow >= 0)
        {
            Orders orders = (Orders) PharmacyTable2.getValueAt(selectedRow, 0);
            if(PharmacyAMOCombo.getSelectedItem() != "")
            {
                String dmName = PharmacyAMOCombo.getSelectedItem().toString();
                DeliveryMan dm = pharmacy.findDeliveryMan(dmName);
                orders.setDeliveryMan(dm);
                JOptionPane.showMessageDialog(null, "Delivery man assigned successfully!");
                populateTable();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Please select a delivery man!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please select a row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_PharmacyAMOAssignDeliveryManButtonActionPerformed

    private void PharmacyTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PharmacyTable2MouseClicked
        // TODO add your handling code here:
        int selectedRow = PharmacyTable2.getSelectedRow();
        if (selectedRow >= 0)
        {
            PharmacyAMOCombo.setEnabled(true);
            PharmacyAMODeleteButton.setEnabled(true);
            PharmacyAMOAssignDeliveryManButton.setEnabled(true);
        }
    }//GEN-LAST:event_PharmacyTable2MouseClicked

    private void PharmacyAMODeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PharmacyAMODeleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = PharmacyTable2.getSelectedRow();
        if (selectedRow >= 0)
        {
            Orders orders = (Orders) PharmacyTable2.getValueAt(selectedRow, 0);
            pharmacy.deleteOrder(orders);
            JOptionPane.showMessageDialog(null, "Order deleted successfully!");
            populateTable();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please select a row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_PharmacyAMODeleteButtonActionPerformed

    private void PharmacyAMOBackButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PharmacyAMOBackButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_PharmacyAMOBackButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PharmacyAMOAssignDeliveryManButton;
    private javax.swing.JButton PharmacyAMOBackButton2;
    private javax.swing.JComboBox<String> PharmacyAMOCombo;
    private javax.swing.JLabel PharmacyAMOCurrentOrdersLabel;
    private javax.swing.JButton PharmacyAMODeleteButton;
    private javax.swing.JLabel PharmacyAMOLabel;
    private javax.swing.JLabel PharmacyAMOLabel2;
    private javax.swing.JLabel PharmacyAMOvalueLabel2;
    private javax.swing.JTable PharmacyTable2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
       DefaultTableModel dtm = (DefaultTableModel)PharmacyTable2.getModel();
        dtm.setRowCount(0);
        if(pharmacy.getOrderDirectory().getOrderList() != null)
        {
            for(Orders orders : pharmacy.getOrderDirectory().getOrderList())
            {
                if(!orders.isStatus())
                {
                    Object[] row = new Object[dtm.getColumnCount()];
                    row[0] = orders;
                    row[1] = orders.getCustomer().getName();
                    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                    row[2] = orders.getOrderDate().format(formatter);
                    if(orders.getDeliveryMan() == null)
                    {
                        row[3] = "";
                    }
                    else
                    {
                        row[3] = orders.getDeliveryMan().getName();
                    }
                    dtm.addRow(row);
                }
            }
        }
        if(dtm.getRowCount() == 0)
            {
                PharmacyAMOCombo.setEnabled(false);
                PharmacyAMOAssignDeliveryManButton.setEnabled(false);
            }
    }
}
