/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharmacyAdminRole;

import Business.EcoSystem;
import Business.Pharmacy.Pharmacy;
import Business.Supplier.Supplier;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vini
 */
public class PharmacyAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmacyAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    Pharmacy pharmacy;
    EcoSystem system;
    Supplier supplier;
    public PharmacyAreaJPanel(JPanel userProcessContainer,UserAccount user, EcoSystem system, Pharmacy pharmacy) {
        initComponents();
        this.userProcessContainer = userProcessContainer;  
        this.userAccount = user;
        this.system = system;
        this.pharmacy=pharmacy;
        /*for(Pharmacy p : system.getPharmacyDirectory().getPharmacyList() )
        {
            
                if(p.getName() == null ? useraccount.getEmployee().getName() == null : p.getName().equals(useraccount.getEmployee().getName()))
                {
                    this.pharmacy = p;
                }
           
        }*/
        
       // txtName.setText(this.pharmacy.getName());
      // system.printout()
//        txtAddress.setText(this.pharmacy.getAddress());
       // txtPhone.setText(this.pharmacy.getPhone());
        
        //valueLabel.setText(this.pharmacy.getName());
        jComboSupplier.addItem("");
        for(Supplier s : system.getSupplierDirectory().getSupplierList())
        {
            jComboSupplier.addItem(s.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboSupplier = new javax.swing.JComboBox<>();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        valueLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel);
        valueLabel.setBounds(678, 60, 150, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Choose a Supplier:");
        add(jLabel2);
        jLabel2.setBounds(240, 120, 210, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("                     Address:");
        add(jLabel4);
        jLabel4.setBounds(230, 420, 230, 50);

        txtName.setEditable(false);
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtName);
        txtName.setBounds(520, 300, 420, 50);

        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtAddress);
        txtAddress.setBounds(520, 420, 420, 50);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("                  Name:");
        add(jLabel5);
        jLabel5.setBounds(250, 300, 210, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pharmacy Work Area");
        add(jLabel1);
        jLabel1.setBounds(370, 10, 580, 40);

        jComboSupplier.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jComboSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSupplierActionPerformed(evt);
            }
        });
        add(jComboSupplier);
        jComboSupplier.setBounds(520, 120, 410, 50);

        enterpriseLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        enterpriseLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        enterpriseLabel.setText("Welcome! ");
        add(enterpriseLabel);
        enterpriseLabel.setBounds(390, 60, 150, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("                            Update Details");
        add(jLabel6);
        jLabel6.setBounds(360, 210, 320, 50);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Review Orders");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(420, 590, 150, 70);

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(850, 590, 150, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pharmacy_Work_Area_Final_Image.jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 10, 1480, 790);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSupplierActionPerformed
        // TODO add your handling code here:
        if(jComboSupplier.getSelectedItem() != "")
        {
            String supp = jComboSupplier.getSelectedItem().toString();
            supplier = system.getSupplierDirectory().findSupplier(supp);
            PharmacyOrderAction poa = new PharmacyOrderAction(userProcessContainer, pharmacy, supplier);
            userProcessContainer.add("CustomerOrder", poa);
            CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_jComboSupplierActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PharmacySummaryJPanel lcj = new PharmacySummaryJPanel(userProcessContainer, userAccount, system, pharmacy);
        userProcessContainer.add("PharmacyOrder", lcj);
        CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if((txtAddress.getText() == "")  )
        {
            JOptionPane.showMessageDialog(null,"Please fill all values!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else
        {
            pharmacy.setAddress(txtAddress.getText());
           // pharmacy.setPhone(txtPhone.getText());

        }
        valueLabel.setText(pharmacy.getName());
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
