/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.AdminRole;

import Business.Role.DeliveryManRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nupoorkorde
 */
public class SystemUpdateEmployee extends javax.swing.JPanel {

    /**
     * Creates new form SystemUpdateEmployee
     */
    private JPanel userProcessContainerSUE;
    private Employee employeeSUE;
    private EcoSystem ecosystemSUE;
    private UserAccount userSUE;
    
    public SystemUpdateEmployee(JPanel userProcessContainer, Employee employee, EcoSystem system) {
        initComponents();
        this.userProcessContainerSUE = userProcessContainer;
        this.employeeSUE = employee;
        this.ecosystemSUE = system;
        this.userSUE = ecosystemSUE.getUserAccountDirectory().findEmployee(employee);
        SystemUEUsernameText.setText(userSUE.getUsername());
        SystemUEPasswordText.setText(userSUE.getPassword());
        SystemUEConfirmPasswordText.setText(userSUE.getPassword());
        SystemUENameText.setText(employee.getName());
        SystemUEPhoneNumberText.setText(employee.getPhone());
        SystemUEAddressText.setText(employee.getAddress());
        if(this.userSUE.getRole().toString().equals("Business.Role.DeliverManRole"))
        {
            SystemUERadio2.setSelected(true);
        }
        else
        {
            SystemUERadio1.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        SystemUELabel1 = new javax.swing.JLabel();
        SystemUENameLabel = new javax.swing.JLabel();
        SystemUENameText = new javax.swing.JTextField();
        SystemUEBackButton = new javax.swing.JButton();
        SystemUEPhoneNumberText = new javax.swing.JTextField();
        SystemUEUsernameText = new javax.swing.JTextField();
        SystemUEPhoneNumberLabel = new javax.swing.JLabel();
        SystemUEPasswordText = new javax.swing.JTextField();
        SystemUEAddressLabel = new javax.swing.JLabel();
        SystemUEConfirmPasswordText = new javax.swing.JTextField();
        SystemUEAddressText = new javax.swing.JTextField();
        SystemUEUsernameLabel = new javax.swing.JLabel();
        SystemUERoleLabel = new javax.swing.JLabel();
        SystemUEPasswordLabel = new javax.swing.JLabel();
        SystemUERadio1 = new javax.swing.JRadioButton();
        SystemUEConfirmPasswordLabel = new javax.swing.JLabel();
        SystemUERadio2 = new javax.swing.JRadioButton();
        SystemUESubmitButton = new javax.swing.JButton();
        SystemUELabel2 = new javax.swing.JLabel();
        SystemUELabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        SystemUELabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        SystemUELabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SystemUELabel1.setText("Update Employees");
        add(SystemUELabel1);
        SystemUELabel1.setBounds(98, 29, 266, 24);

        SystemUENameLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SystemUENameLabel.setText("Name:");
        add(SystemUENameLabel);
        SystemUENameLabel.setBounds(19, 214, 144, 15);

        SystemUENameText.setEditable(false);
        SystemUENameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(SystemUENameText);
        SystemUENameText.setBounds(209, 208, 160, 18);

        SystemUEBackButton.setText("< Back");
        SystemUEBackButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SystemUEBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemUEBackButtonActionPerformed(evt);
            }
        });
        add(SystemUEBackButton);
        SystemUEBackButton.setBounds(136, 404, 42, 22);

        SystemUEPhoneNumberText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(SystemUEPhoneNumberText);
        SystemUEPhoneNumberText.setBounds(209, 248, 160, 18);

        SystemUEUsernameText.setEditable(false);
        SystemUEUsernameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(SystemUEUsernameText);
        SystemUEUsernameText.setBounds(209, 79, 160, 18);

        SystemUEPhoneNumberLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SystemUEPhoneNumberLabel.setText("Phone Number:");
        add(SystemUEPhoneNumberLabel);
        SystemUEPhoneNumberLabel.setBounds(19, 254, 144, 15);

        SystemUEPasswordText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(SystemUEPasswordText);
        SystemUEPasswordText.setBounds(209, 128, 160, 18);

        SystemUEAddressLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SystemUEAddressLabel.setText("Address:");
        add(SystemUEAddressLabel);
        SystemUEAddressLabel.setBounds(19, 294, 144, 15);

        SystemUEConfirmPasswordText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(SystemUEConfirmPasswordText);
        SystemUEConfirmPasswordText.setBounds(209, 168, 160, 18);

        SystemUEAddressText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(SystemUEAddressText);
        SystemUEAddressText.setBounds(209, 288, 160, 18);

        SystemUEUsernameLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SystemUEUsernameLabel.setText("Username: ");
        add(SystemUEUsernameLabel);
        SystemUEUsernameLabel.setBounds(19, 85, 144, 15);

        SystemUERoleLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SystemUERoleLabel.setText("Role:");
        add(SystemUERoleLabel);
        SystemUERoleLabel.setBounds(19, 337, 144, 15);

        SystemUEPasswordLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SystemUEPasswordLabel.setText("Password: ");
        add(SystemUEPasswordLabel);
        SystemUEPasswordLabel.setBounds(19, 134, 144, 15);

        buttonGroup1.add(SystemUERadio1);
        SystemUERadio1.setText("Pharmacy Manager");
        SystemUERadio1.setEnabled(false);
        add(SystemUERadio1);
        SystemUERadio1.setBounds(209, 328, 160, 21);

        SystemUEConfirmPasswordLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SystemUEConfirmPasswordLabel.setText("Confirm Password:");
        add(SystemUEConfirmPasswordLabel);
        SystemUEConfirmPasswordLabel.setBounds(19, 174, 144, 15);

        buttonGroup1.add(SystemUERadio2);
        SystemUERadio2.setText("Delivery Man");
        SystemUERadio2.setEnabled(false);
        add(SystemUERadio2);
        SystemUERadio2.setBounds(209, 357, 160, 21);

        SystemUESubmitButton.setText("Submit");
        SystemUESubmitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SystemUESubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemUESubmitButtonActionPerformed(evt);
            }
        });
        add(SystemUESubmitButton);
        SystemUESubmitButton.setBounds(209, 404, 160, 22);
        add(SystemUELabel2);
        SystemUELabel2.setBounds(19, 11, 0, 99);

        SystemUELabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Manage_Emplyee_Final_IMAGE.png"))); // NOI18N
        add(SystemUELabel);
        SystemUELabel.setBounds(0, 0, 1230, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void SystemUEBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemUEBackButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainerSUE.remove(this);
        CardLayout layout = (CardLayout) userProcessContainerSUE.getLayout();
        layout.previous(userProcessContainerSUE);
    }//GEN-LAST:event_SystemUEBackButtonActionPerformed

    private void SystemUESubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemUESubmitButtonActionPerformed
        // TODO add your handling code here:
        if(validateThisSUE())
        {
            userSUE.setPassword(SystemUEPasswordText.getText());
            employeeSUE.setAddress(SystemUEAddressText.getText());
            employeeSUE.setPhone((SystemUEPhoneNumberText.getText()));
            JOptionPane.showMessageDialog(null, "Details for " + employeeSUE.getName()+ " updated successfully!");
        }
        else
        {
            return;
        }
    }//GEN-LAST:event_SystemUESubmitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SystemUEAddressLabel;
    private javax.swing.JTextField SystemUEAddressText;
    private javax.swing.JButton SystemUEBackButton;
    private javax.swing.JLabel SystemUEConfirmPasswordLabel;
    private javax.swing.JTextField SystemUEConfirmPasswordText;
    private javax.swing.JLabel SystemUELabel;
    private javax.swing.JLabel SystemUELabel1;
    private javax.swing.JLabel SystemUELabel2;
    private javax.swing.JLabel SystemUENameLabel;
    private javax.swing.JTextField SystemUENameText;
    private javax.swing.JLabel SystemUEPasswordLabel;
    private javax.swing.JTextField SystemUEPasswordText;
    private javax.swing.JLabel SystemUEPhoneNumberLabel;
    private javax.swing.JTextField SystemUEPhoneNumberText;
    private javax.swing.JRadioButton SystemUERadio1;
    private javax.swing.JRadioButton SystemUERadio2;
    private javax.swing.JLabel SystemUERoleLabel;
    private javax.swing.JButton SystemUESubmitButton;
    private javax.swing.JLabel SystemUEUsernameLabel;
    private javax.swing.JTextField SystemUEUsernameText;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables

    private boolean validateThisSUE() {
        String regex = "\\d{10}";
        if(("".equals(SystemUEPasswordText.getText())) || ("".equals(SystemUEConfirmPasswordText.getText())) 
                || ("".equals(SystemUEPhoneNumberText.getText())) || ("".equals(SystemUEAddressText.getText())))
        {
            JOptionPane.showMessageDialog(null,"Please fill all details!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else if(!(SystemUEPasswordText.getText().equals(SystemUEConfirmPasswordText.getText())))
        {
            JOptionPane.showMessageDialog(null,"Passwords do not match!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else if(!(SystemUEPhoneNumberText.getText().matches(regex)))
        {
            JOptionPane.showMessageDialog(null,"Phone number must have only 10 digits!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else
        {
            return true;
        }
    }
}
