/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vini
 */
public class AddRestaurantJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddRestaurantJPanel
     */
    private final RestaurantDirectory restDirectory;
    private final JPanel container;
    private final EcoSystem system;
    
    Restaurant  rest = new Restaurant();
    public AddRestaurantJPanel(JPanel container, EcoSystem system, RestaurantDirectory restDir) {
        initComponents();
        this.restDirectory = restDir;
        this.system = system;
        this.container = container;
      //  System.out.println("-- "+system);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pwRestPass = new javax.swing.JPasswordField();
        txtRestUserName = new javax.swing.JTextField();
        txtRestName = new javax.swing.JTextField();
        lblRestContact = new javax.swing.JLabel();
        lblRestPass = new javax.swing.JLabel();
        lblRestUserName = new javax.swing.JLabel();
        lblRestName = new javax.swing.JLabel();
        txtRestAddr = new javax.swing.JTextField();
        lblAddRest = new javax.swing.JLabel();
        lblRestAddr = new javax.swing.JLabel();
        pbRestPassStr = new javax.swing.JProgressBar();
        txtRestContact = new javax.swing.JTextField();
        btnAddRest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setForeground(new java.awt.Color(0, 51, 51));

        pwRestPass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pwRestPass.setForeground(new java.awt.Color(0, 51, 51));
        pwRestPass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pwRestPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwRestPassActionPerformed(evt);
            }
        });
        pwRestPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwRestPassKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwRestPassKeyTyped(evt);
            }
        });

        txtRestUserName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtRestUserName.setForeground(new java.awt.Color(0, 51, 51));
        txtRestUserName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtRestName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtRestName.setForeground(new java.awt.Color(0, 51, 51));
        txtRestName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblRestContact.setBackground(new java.awt.Color(204, 255, 255));
        lblRestContact.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblRestContact.setForeground(new java.awt.Color(0, 51, 51));
        lblRestContact.setText("Contact No :");

        lblRestPass.setBackground(new java.awt.Color(204, 255, 255));
        lblRestPass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblRestPass.setForeground(new java.awt.Color(0, 51, 51));
        lblRestPass.setText("Set Password :");

        lblRestUserName.setBackground(new java.awt.Color(204, 255, 255));
        lblRestUserName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblRestUserName.setForeground(new java.awt.Color(0, 51, 51));
        lblRestUserName.setText("Set Username :");

        lblRestName.setBackground(new java.awt.Color(204, 255, 255));
        lblRestName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblRestName.setForeground(new java.awt.Color(0, 51, 51));
        lblRestName.setText("Restaurant Name :");

        txtRestAddr.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtRestAddr.setForeground(new java.awt.Color(0, 51, 51));
        txtRestAddr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblAddRest.setBackground(new java.awt.Color(204, 255, 255));
        lblAddRest.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAddRest.setForeground(new java.awt.Color(0, 51, 51));
        lblAddRest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddRest.setText("Add New Restaurant");

        lblRestAddr.setBackground(new java.awt.Color(204, 255, 255));
        lblRestAddr.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblRestAddr.setForeground(new java.awt.Color(0, 51, 51));
        lblRestAddr.setText("Address :");

        pbRestPassStr.setBackground(new java.awt.Color(255, 255, 255));
        pbRestPassStr.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        pbRestPassStr.setForeground(new java.awt.Color(0, 51, 51));
        pbRestPassStr.setMaximum(13);
        pbRestPassStr.setMinimum(1);
        pbRestPassStr.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pbRestPassStrStateChanged(evt);
            }
        });

        txtRestContact.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtRestContact.setForeground(new java.awt.Color(0, 51, 51));
        txtRestContact.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAddRest.setBackground(new java.awt.Color(204, 255, 255));
        btnAddRest.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnAddRest.setForeground(new java.awt.Color(0, 51, 51));
        btnAddRest.setText("Add");
        btnAddRest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRestActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 255, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 51, 51));
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAddRest)
                .addGap(339, 339, 339))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRestAddr)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblRestName)
                        .addComponent(lblRestUserName, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(lblRestPass)
                    .addComponent(lblRestContact))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRestAddr, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pbRestPassStr, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                            .addComponent(txtRestContact)
                            .addComponent(txtRestUserName)
                            .addComponent(pwRestPass)
                            .addComponent(txtRestName))
                        .addGap(111, 111, 111))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnBack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(btnAddRest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblAddRest)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRestName)
                    .addComponent(txtRestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRestUserName)
                    .addComponent(txtRestUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRestPass)
                    .addComponent(pwRestPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbRestPassStr, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRestContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRestContact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRestAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRestAddr))
                .addGap(26, 26, 26)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(btnAddRest)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pwRestPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwRestPassActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_pwRestPassActionPerformed

    private void pwRestPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwRestPassKeyReleased
        // TODO add your handling code here
    }//GEN-LAST:event_pwRestPassKeyReleased

    private void pwRestPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwRestPassKeyTyped
        // TODO add your handling code here:
        int pwSize = pwRestPass.getText().length();
        pbRestPassStr.setValue(pwSize);
    }//GEN-LAST:event_pwRestPassKeyTyped

    private void pbRestPassStrStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pbRestPassStrStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_pbRestPassStrStateChanged

    private void btnAddRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRestActionPerformed
        // TODO add your handling code here:

        String custName = txtRestName.getText();
        String custContact = txtRestContact.getText();
        String custAddr = txtRestAddr.getText();
        String custUserName = txtRestUserName.getText();
        String custPass = String.valueOf(pwRestPass.getPassword());

        if( custName.isEmpty() || custContact.isEmpty() || custAddr.isEmpty() ||
            custUserName.isEmpty() || custPass.isEmpty()  ) {
            JOptionPane.showMessageDialog(null, "Kindly Enter all the required fields!");
        }   else if (!system.validateMobileNo(custContact)) {
            JOptionPane.showMessageDialog(null, "Kindly enter a Valid Contact Number.");
        }    else if (!system.getUserAccountDirectory().checkIfUsernameIsUnique(custUserName)) {
            JOptionPane.showMessageDialog(null, "Entered User Name is already mapped to another Restaurant");
        }     else if (!restDirectory.isContactNoUnique(custContact)) {
            JOptionPane.showMessageDialog(null, "Entered Contact No is already mapped to another Restaurant.");
        }   else {

            rest.setRestName(custName);
            rest.setRestAddress(custAddr);
            rest.setRestContact(custContact);
            restDirectory.addRestaurant(rest);
            Employee employee = system.getEmployeeDirectory().createEmployee(rest.getRestNo() );
            system.setRestaurantDirectory(restDirectory);
            UserAccount account = system.getUserAccountDirectory().createUserAccount(custUserName, custPass, employee, new AdminRole());
            JOptionPane.showMessageDialog(null, "New Restaurant "+account.getUsername()+" added to the System Successfully!");
            clearAllFields();
        }
    }//GEN-LAST:event_btnAddRestActionPerformed
 public void clearAllFields() {
        txtRestName.setText("");
        txtRestAddr.setText("");
        txtRestContact.setText("");
        txtRestUserName.setText("");
        pwRestPass.setText("");
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageRestaurantsJPanel manageRestJPanel = (ManageRestaurantsJPanel) component;
        manageRestJPanel.populateRestaurantsTable();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRest;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblAddRest;
    private javax.swing.JLabel lblRestAddr;
    private javax.swing.JLabel lblRestContact;
    private javax.swing.JLabel lblRestName;
    private javax.swing.JLabel lblRestPass;
    private javax.swing.JLabel lblRestUserName;
    private javax.swing.JProgressBar pbRestPassStr;
    private javax.swing.JPasswordField pwRestPass;
    private javax.swing.JTextField txtRestAddr;
    private javax.swing.JTextField txtRestContact;
    private javax.swing.JTextField txtRestName;
    private javax.swing.JTextField txtRestUserName;
    // End of variables declaration//GEN-END:variables
}
