

package userinterface.RestaurantAdminRole;


import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Order.Menu;
import Business.Order.OrderDirectory;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    private final JPanel userProcessContainer;
    private final RestaurantDirectory restaurantDirectory;
    private final EcoSystem system;
    private final Menu menuDirectory;
    private final OrderDirectory orderDirectory;
    private final UserAccount account;
    private final DeliveryManDirectory deliveryManDirectory;
    
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system, RestaurantDirectory restaurantDirectory, DeliveryManDirectory deliveryManDirectory, Menu menuDirectory, OrderDirectory orderDirectory) {
        initComponents();
        lblRestName.setText(account.getUsername());
        lblRestAdmin.setText(account.getEmployee().getName()+" 's Admin Page");
        this.userProcessContainer = userProcessContainer;
        this.restaurantDirectory = restaurantDirectory;
        this.system = system;
        this.menuDirectory = menuDirectory;
        this.orderDirectory = orderDirectory;
        this.account = account;
        this.deliveryManDirectory = deliveryManDirectory;
      
        //valueLabel.setText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRestAdmin = new javax.swing.JLabel();
        btnRestInfo = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnOrders = new javax.swing.JButton();
        lblRestName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setForeground(new java.awt.Color(0, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRestAdmin.setBackground(new java.awt.Color(204, 255, 255));
        lblRestAdmin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblRestAdmin.setForeground(new java.awt.Color(0, 51, 51));
        lblRestAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestAdmin.setText("Restaurant Management Screen");
        add(lblRestAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        btnRestInfo.setBackground(new java.awt.Color(204, 255, 255));
        btnRestInfo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnRestInfo.setForeground(new java.awt.Color(0, 51, 51));
        btnRestInfo.setText("Manage Restaurant Information");
        btnRestInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestInfoActionPerformed(evt);
            }
        });
        add(btnRestInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 410, -1));

        btnMenu.setBackground(new java.awt.Color(204, 255, 255));
        btnMenu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(0, 51, 51));
        btnMenu.setText("Manage menu");
        btnMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 410, -1));

        btnOrders.setBackground(new java.awt.Color(204, 255, 255));
        btnOrders.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnOrders.setForeground(new java.awt.Color(0, 51, 51));
        btnOrders.setText("Manage Orders");
        btnOrders.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersActionPerformed(evt);
            }
        });
        add(btnOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 410, -1));

        lblRestName.setBackground(new java.awt.Color(204, 255, 255));
        lblRestName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblRestName.setForeground(new java.awt.Color(0, 51, 51));
        lblRestName.setText("Restaurant");
        add(lblRestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 60, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestInfoActionPerformed
        // TODO add your handling code here:
         RestInfoPanel restInfoJPanel = new RestInfoPanel(userProcessContainer, account, system, restaurantDirectory);
        userProcessContainer.add("restInfoJPanel", restInfoJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRestInfoActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        RestMenuJPanel restMenuJPanel = new RestMenuJPanel(userProcessContainer, account, system, restaurantDirectory, menuDirectory);
        userProcessContainer.add("restMenuJPanel", restMenuJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersActionPerformed
        RestOrderJPanel restOrderJPanel = new RestOrderJPanel(userProcessContainer, account, system, restaurantDirectory, deliveryManDirectory, menuDirectory,orderDirectory);
        userProcessContainer.add("restOrderJPanel", restOrderJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOrdersActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnOrders;
    private javax.swing.JButton btnRestInfo;
    private javax.swing.JLabel lblRestAdmin;
    private javax.swing.JLabel lblRestName;
    // End of variables declaration//GEN-END:variables
    
}
