

package userinterface.RestaurantAdminRole;


import Business.DeliveryMan.DeliveryManStore;
import Business.EcoSystem;
import Business.Order.Menu;
import Business.Order.OrderStore;
import Business.Restaurant.RestaurantStore;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  dhrit
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    private final JPanel userProcessContainer;
    private final RestaurantStore restaurantDirectory;
    private final EcoSystem system;
    private final Menu menuDirectory;
    private final OrderStore orderDirectory;
    private final UserAccount account;
    private final DeliveryManStore deliveryManDirectory;
    
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system, RestaurantStore restaurantDirectory, DeliveryManStore deliveryManDirectory, Menu menuDirectory, OrderStore orderDirectory) {
        initComponents();
        lblRestName.setText(account.getUsername());
        lblRestAdmin.setText(account.getEmployee().getName()+" 's Admin Page");
        this.userProcessContainer = userProcessContainer;
        this.restaurantDirectory = restaurantDirectory;
        this.system = system;
        this.menuDirectory = menuDirectory;
        this.orderDirectory = orderDirectory;
        this.account = account;
        this.deliveryManDirectory = deliveryManDirectory;
      
        //valueLabel.setText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRestAdmin = new javax.swing.JLabel();
        btnRestaurantInfo = new javax.swing.JButton();
        btnRestMenu = new javax.swing.JButton();
        btnRestManageOrders = new javax.swing.JButton();
        lblRestName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setForeground(new java.awt.Color(0, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRestAdmin.setBackground(new java.awt.Color(204, 255, 255));
        lblRestAdmin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblRestAdmin.setForeground(new java.awt.Color(0, 51, 51));
        lblRestAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestAdmin.setText("Restaurant Management Screen");
        add(lblRestAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        btnRestaurantInfo.setBackground(new java.awt.Color(204, 255, 255));
        btnRestaurantInfo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnRestaurantInfo.setForeground(new java.awt.Color(0, 51, 51));
        btnRestaurantInfo.setText("Manage Restaurant Information");
        btnRestaurantInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurantInfoActionPerformed(evt);
            }
        });
        add(btnRestaurantInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 180, -1));

        btnRestMenu.setBackground(new java.awt.Color(204, 255, 255));
        btnRestMenu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnRestMenu.setForeground(new java.awt.Color(0, 51, 51));
        btnRestMenu.setText("Manage menu");
        btnRestMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRestMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestMenuActionPerformed(evt);
            }
        });
        add(btnRestMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 180, -1));

        btnRestManageOrders.setBackground(new java.awt.Color(204, 255, 255));
        btnRestManageOrders.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnRestManageOrders.setForeground(new java.awt.Color(0, 51, 51));
        btnRestManageOrders.setText("Manage Orders");
        btnRestManageOrders.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRestManageOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestManageOrdersActionPerformed(evt);
            }
        });
        add(btnRestManageOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 180, -1));

        lblRestName.setBackground(new java.awt.Color(204, 255, 255));
        lblRestName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblRestName.setForeground(new java.awt.Color(0, 51, 51));
        lblRestName.setText("Restaurant");
        add(lblRestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestaurantInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurantInfoActionPerformed
        // TODO add your handling code here:
         RestInfoPanel restInfoJPanel = new RestInfoPanel(userProcessContainer, account, system, restaurantDirectory);
        userProcessContainer.add("restInfoJPanel", restInfoJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRestaurantInfoActionPerformed

    private void btnRestMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestMenuActionPerformed
        RestMenuJPanel restMenuJPanel = new RestMenuJPanel(userProcessContainer, account, system, restaurantDirectory, menuDirectory);
        userProcessContainer.add("restMenuJPanel", restMenuJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRestMenuActionPerformed

    private void btnRestManageOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestManageOrdersActionPerformed
        RestOrderJPanel restOrderJPanel = new RestOrderJPanel(userProcessContainer, account, system, restaurantDirectory, deliveryManDirectory, menuDirectory,orderDirectory);
        userProcessContainer.add("restOrderJPanel", restOrderJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRestManageOrdersActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRestManageOrders;
    private javax.swing.JButton btnRestMenu;
    private javax.swing.JButton btnRestaurantInfo;
    private javax.swing.JLabel lblRestAdmin;
    private javax.swing.JLabel lblRestName;
    // End of variables declaration//GEN-END:variables
    
}
